### ISSUE TITLE
Is a libsodium 1.0.19 release planned?

### ISSUE THREAD

**Issue by past-due** [jedisct1/libsodium#1028]
There have been a lot of improvements and fixes since the initial libsodium 1.0.18 release, and the rolling "libsodium 1.0.18-stable" releases are quite nice.

However, there are various situations in which having an immutable release tarball / Git tag are quite helpful (or required). And there are various downstreams that won't really pick up many / any of these improvements until the release number is incremented.

For those (and other) reasons, I'd like to kindly request consideration of making an official "1.0.19" release that packages up all of the improvements since that initial 1.0.18 release, when appropriate / possible.

(Also, a huge thank you for all the incredible work on a fantastic library. 🥳)

**Comment by jedisct1** [comment]
Yes, there will be more point releases.

The H2C specification being a moving target was one of the blockers, and the libsodium API for it just had to be changed a couple days ago due to discrepancies between that specification and the way it is used in protocols.

Better support for Apple Silicon, at least add AES-GCM and possibly faster AEGIS are also required for a new release. And support for batch signatures could be nice to have, too, if only for parity with the Zig standard library. But once done yes, a new version will be cut.

Meanwhile, you can always pin specific commits from `stable`.
