### ISSUE TITLE
Linker command failed - android-armv7 script

### ISSUE THREAD

**Issue by cmonfortep** [jedisct1/libsodium#1251]
I'm trying to run the script to generate an aar for Android, and I'm getting an error when the script tries to compile the library on the armv7 architecture.

First I tried executing `android-aar.sh` script, and it generated an `aar` but armv7 failed.
Then I tried executing `android-armv7-a.sh`, and I get a bunch of errors (e.g: `libaesni.a: member at 8 is not an ELF object`), with a final clang error saying `linker command failed with exit code 1`.

Rest of the architectures script work without issues (arm8, x86, and x86_64), so I assume this is something specific of armv7.

Also, in case it helps, I'm running those scripts from MacBook pro, darwin kernel x86_64.

**Comment by jedisct1** [comment]
Everything seems to be fine in CI: 

https://github.com/jedisct1/libsodium/blob/176923f6ecd846893fa0070578ec1ba152e78c31/.github/workflows/ci.yml#L158-L180

https://github.com/jedisct1/libsodium/actions/runs/4009408847/jobs/6884725366

Are you using the same NDK version? (r25b)

**Comment by cmonfortep** [comment]
Thanks for the quick response.
The latest version of git, yes, but an old version of ndk (`21.4.7075529`, we use that version to compile other internal c libraries). I've just downloaded ndk version 25 and I confirm it works.

So that confirms the issue is the ndk version I was using. I will need to check with the team if we can bump ndk version. Are you aware of why using ndk 25 fixes it?

**Comment by ReenigneCA** [comment]
The quick answer is that the toolchain was before the current aar script was written so it was never tested against. I'm more surprised that any of the scripts work to be honest the old libsodium scripts used to create toolchains for each platform, which was the legacy approach to the ndk (it was pretty crazy you'd have a huge toolchain directory structure created for each version of each thin you'd compile). Looking at the [ndk changelog](https://developer.android.com/ndk/downloads/revision_history) it appears that the version you're using was a transitional version between the old and new approaches: 

"The legacy toolchain install paths will be removed over the coming releases. These paths have been obsolete since NDK r19 and take up a considerable amount of space in the NDK. The paths being removed are"

So I'd guess that some important files moved around in the process or maybe even were added or renamed or something. It is likely possible to get it working either by modifying some flags in the current scripts or going back to the previous versions of the scripts and modifying them to work with the script that packs the outputs into the AAR. The old build scripts are still bundled in the [stable release on the libsodium site](https://download.libsodium.org/libsodium/releases/).

**Comment by cmonfortep** [comment]
Thanks for the explanation @ReenigneCA 👍
