### ISSUE TITLE
Build for 32bit Linux platforms disables AES256-GCM, even though the CPU and GCC supports it

### ISSUE THREAD

**Issue by jan-moravec** [jedisct1/libsodium#1395]
I am compiling libsodium from source on 32bit Debian.

Configure includes following check: https://github.com/jedisct1/libsodium/blob/master/configure.ac#L750
This will disable `HAVE_AVX_ASM` for non 64bit platforms. This is not completely correct, even 32bit platforms support AVX.

My main issue is then here: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/runtime.c#L254

Even though the CPU has AVX, which could be checked correctly in runtime (if there was the `HAVE_AVX_ASM`), it is mark as non-available. And this causes the following function to return AES256-GCM as unavailable: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c#L1008

AES256-GCM functions are working correctly, only the check is wrong.

**Comment by jedisct1** [comment]
Here's the thing. The i386 platform is not very common any more.

I don't have any simple way to test code on that platform. Besides AES-GCM, there are probably other places assuming that x86_64 is required for AVX. Similar assumptions are made for aarch64. This is incorrect, but I really prefer being safe than shipping untested code that may not work.

This is something I may revisit if I really have spare time, or as part of a support contract, but otherwise, this is very very very low priority, especially since aegis is a better alternative and works on i386.

**Comment by jan-moravec** [comment]
I understand, thank you for fast reply.
