### ISSUE TITLE
Demo program

### ISSUE THREAD

**Issue by GraxRabble** [jedisct1/libsodium#145]
[Here's the Gist](https://gist.github.com/GraxRabble/cd9b3a2a1072522d6ba2)

It's a c program which demonstrates all the high level cryptography and hashing functions within the library. This includes function specific padding and summaries on what is considered safe practice (eg. counter nonce).

Any idea where you want to fit this in?

**Comment by jedisct1** [comment]
It's been merged in the `examples` folder. However, this is not part of the distribution (referenced in automake's makefiles) yet because many functions are still missing.

We should at least try to cover all the high-level functions, with the exception of the ones documented in the "advanced" section of the documentation, that can be added later on.
