### ISSUE TITLE
Implicit conversion issues with Cocoapods for iOS

### ISSUE THREAD

**Issue by jamesstidard** [jedisct1/libsodium#203]
Hi all,

I'm using cocoapods to manage my dependancies and have included the libsodium pod in my project. Xcode is flagging a number (46) of warnings about 64 to 32 bit conversions. 

I was wondering if this is an issue or, possibly, intentional low-level wizardry.

Thanks,
James

**Comment by gabriel** [comment]
The libsodium cocoapod is showing these warnings (in 1.0.2).
![2015-06-16 at 1 05 pm](https://cloud.githubusercontent.com/assets/2669/8193226/77424be6-1428-11e5-97e3-8efc399da53d.png)

**Comment by jedisct1** [comment]
You can safely ignore this,

**Comment by gabriel** [comment]
Cocoapods recently made it so that it won't publish pods with compiler warnings, unless you override with `--allow-warnings`. And this includes pods that include other pods. Basically they are trying to help projects compile cleanly (or at least promote clean builds). While its easy to override, we could use a compiler pragma for these specific lines?

```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconversion"
...
#pragma clang diagnostic pop
```

This might be bad idea though?
