### ISSUE TITLE
Crosscheck with TweetNaCl?

### ISSUE THREAD

**Issue by patlecat** [jedisct1/libsodium#226]
Has anyone cross-checked the libSodium code with the newest implementation of Daniel J. Bernstein published last year in his new **TweetNaCl** that can be found in the link below? I mean the code from the NaCl crypto site hasn't been updated for a very long while now. Might be a good idea then to see what undocumented refinements and bugfixes he might have added to it :D 

* [TweetNaCl code](http://tweetnacl.cr.yp.to/software.html)
* [The paper on TweetNaCl](http://tweetnacl.cr.yp.to/tweetnacl-20140917.pdf)

**Comment by jedisct1** [comment]
TweetNaCl code is completely different. While NaCl was focused on performance, TweetNaCl goal was to get the source code as short as possible.

TweetNaCl didn't introduce any bugfixes for NaCl since the code bases are completely different. TweetNaCl even initially [introduced bugs on its own](http://blog.skylable.com/2014/05/tweetnacl-carrybit-bug/). 

The major change (and incompatibility) is that TweetNaCl replaced NaCl's prototype signature system with ed25519. 

The good news is that the change was anticipated by sodium : `crypto_sign()` uses ed25519 since the very first release of the library, and the keys and signatures happen to be compatible TweetNaCl.

As in cross-checking implementations, this is the goal of the [libsodium-validation](https://github.com/jedisct1/libsodium-validation) project: create large amounts of test vectors produced by multiple implementations in order to cross-check their interoperability. Granted, I haven't updated this project for a while, but vectors generated by TweetNaCl will definitely be added.

**Comment by patlecat** [comment]
Yes I know that the focus is very different. And I'm glad that you know that nothing relevant changed for libSodium with it. I know about the addition of ed25519 which hasn't yet undergone auditing in NaCl. 

* Is there a newer version of NaCl than the 2011 bzip from the website?

**Comment by jedisct1** [comment]
NaCl didn't see any newer releases, but individual implementations had some updates, either in SuperCop or in dedicated repositories. libsodium picked up these updates.

**Comment by patlecat** [comment]
Ok, I just found by reading the paper on TweetNaCl that they have optimized a few things like code lines reduction that are also applicable to NaCl and who knows what else they added to it but not published. Unfortunately Bernstein and his team are academic researchers and not software-engineers so once they published their paper for them their work is done ... but a software-engineer's jobs has just begun ;)

**Comment by jedisct1** [comment]
djb is also an incredibly good software engineer, but he hasn't found how to slow down time. Yet.

**Comment by patlecat** [comment]
Maybe he is incredibly good (but then how can you find it credible?), I cannot judge his qualities, but maintenance of this code is not on his agenda. And that is often the case with academic researchers, that's what I meant. This may hurt the community in the same way as it did harm OpenSSL in the long run.
