### ISSUE TITLE
SEGFAULT in test sodium_utils2 on Ubuntu 14.04

### ISSUE THREAD

**Issue by srushingiv** [jedisct1/libsodium#281]
make check returns the following:

    ../../build-aux/test-driver: line 107: 28079 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
    FAIL: sodium_utils2
    PASS: sodium_utils3
    ============================================================================
    Testsuite summary for libsodium 1.0.3
    ============================================================================
    # TOTAL: 57
    # PASS:  56
    # SKIP:  0
    # XFAIL: 0
    # FAIL:  1
    # XPASS: 0
    # ERROR: 0
    ============================================================================
    See test/default/test-suite.log
    Please report to https://github.com/jedisct1/libsodium/issues
    ============================================================================
    make[4]: *** [test-suite.log] Error 1
    make[4]: Leaving directory `/home/samr/libsodium-1.0.3/test/default'
    make[3]: *** [check-TESTS] Error 2
    make[3]: Leaving directory `/home/samr/libsodium-1.0.3/test/default'
    make[2]: *** [check-am] Error 2
    make[2]: Leaving directory `/home/samr/libsodium-1.0.3/test/default'
    make[1]: *** [check-recursive] Error 1
    make[1]: Leaving directory `/home/samr/libsodium-1.0.3/test'
    make: *** [check-recursive] Error 1

**Comment by jedisct1** [comment]
Hi,

Can you share the `config.log` and `test/default/sodium_utils2.res` files?

**Comment by srushingiv** [comment]
Sadly, i was in a time crunch and after trying a couple different revisions (erasing the previous attempts as i went), i just decided to skip the make check step and everything installed ok. I suspect one of the unit tests make use more memory than my EC2 instance has available.

**Comment by jedisct1** [comment]
This test is a bit special, as it tests the guarded memory allocation functions, and intentionally triggers a segmentation violation (the expected behavior after an out-of-bounds access when using these allocation functions).

The test is supposed to catch the signal. However, additional tools to prevent/detect out-of-bound accesses can kill the test before it has a change to evaluate the signal handler.
gcc & clang address sanitizer is know to cause this, and the test logs a warning in the `.res` file about this when address sanitizer is detected.

Maybe the EC2 image you chose has address sanitizer turned on by default. I'm closing this ticket as given that it happened in this particular test, it's likely to be what happened, but it would be great if you could confirm this, or at least share the files mentioned above.
