### ISSUE TITLE
Assembly version of poly1305 for mips32

### ISSUE THREAD

**Issue by mwarning** [jedisct1/libsodium#289]
There is an assembly version of poly1305 for mips32r2 (little/big endian).
It would be very helpful for embedded devices.

https://github.com/cjdelisle/poly1305-mips32r2-donna

**Comment by jedisct1** [comment]
mips-optimized implementations might be added, but probably not in the near future.

Unfortunately, I don't have mips hardware to test them, and Qemu is not an option to make sure that an implementation works as expected, especially due to alignment constraints. Not a way to measure performance either.
