### ISSUE TITLE
Feature request: Constant time check if zero

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#291]
Some cryptographic algorithms (like the axolotl ratchet) require checking if a key is `<none>`. I implemented this by filling the entire key with zeroes.

But now to check if it is `<none>`, I need a constant time algorithm to check this, so I currently do the following:
```C
unsigned char *key = get_key_from_somewhere();
unsigned char none[crypto_secretbox_keybytes];
sodium_memzero(none, sizeof(none));
//check if none
if (sodium_memcmp(key, none, sizeof(none)) == 0) {
    puts("Key is <none>!");
} else {
    puts("Key is not <none>");
}
```

It would be nice to have a function that runs in constant time and checks if an array of `unsigned char` is entirely filled with zeroes (or with some other value).

**Comment by chmike** [comment]
Le 29/08/2015 09:55, Max Bruckner a écrit :
>
> Some cryptographic algorithms (like the axolotl ratchet) require 
> checking if a key is |<none>|. I implemented this by filling the 
> entire key with zeroes.
>
> But now to check if it is |<none>|, I need a constant time algorithm 
> to check this, so I currently do the following:
>
> unsigned  char  *key = get_key_from_somewhere();
> unsigned  char  none[crypto_secretbox_keybytes];
> sodium_memzero(none,sizeof(none));
> //check if none
> if  (sodium_memcmp(key, none,sizeof(none)) ==0) {
>      puts("Key is <none>!");
> }else  {
>      puts("Key is not <none>");
> }
>
> It would be nice to have a function that runs in constant time and 
> checks if an array of |unsigned char| is entirely filled with zeroes 
> (or with some other value).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jedisct1/libsodium/issues/291>.
>
This is too simple to do.

/* Return 1 if filled with zero, 0 otherwise
   * Requires m is not NULL
   * Return 0 when len is zero
   */
int is_filled_with_zero(const void *m, size_t len) {
     int res = 0;
     const char *p = (const char*)m;
     while (len--) res |= *p++;
     return res == 0; // or -((res - 1) >> 8)  to avoid test
}

/* Return 1 if filled with char c, 0 otherwise
   * Requires m is not NULL
   * Return 0 when len is zero
   */
int is_filled_with_char(const void *m, size_t len, char c) {
     int res = 0;
     const char *p = (const char*)m;
     while (len--)  res |= c ^ *p++;
     return res == 0; // or -((res - 1) >> 8)  to avoid test
}

Usage example :

if (is_filled_with_zero(stored_pwd_hash, pwd_hash_len) {
     /* account locked */
}

Not sure if this would be a useful addition to libsodium.
The simplicity of the library is one of its strength.
Minimize maintenance depth and learning effort.

-- 
Bien cordialement,

Ch. Meessen

**Comment by FSMaxB** [comment]
It would be trivial for me to implement something which looks like it's constant time, but I have no idea what compilers will do with it, potentioally optimising it in a way that isn't.

I really don't want to touch any of the keys handled in my program manually in any way, shape or form, only through libsodium because I don't want to have the responsibility to ensure that there are no such side channels because I don't have the required knowledge and experience with this kind of stuff.

**Comment by cfcs** [comment]
The safest way to do this is probably `volatile` inline ASM implementing @chmike's AND-method, which would mean maintaining cross-platform assembly code -- imho that justifies its existence as a libsodium function rather than something programmers will have to implement as a shared object for every project, especially when using high-level programming languages where inline asm is not readily available.

**Comment by FSMaxB** [comment]
Looking at the source code, the current implementation of `sodium_memcmp` isn't written in assemly either: https://github.com/jedisct1/libsodium/blob/8fa4ef139122bb819d388a464c3fe4f759d06311/src/libsodium/sodium/utils.c#L85

It seems like it's not important to have it run in constant time, but the runtime mustn't depend on the content of the array and there mustn't be any conditional jumps that depend on the content if I understand it correctly.

**Comment by jedisct1** [comment]
This is very specific, yet fairly easy to implement, and you can also just use `sodium_memcmp()` against a static zeroed array to achieve what you want.

So I don't think this is worth adding to the core library.

**Comment by FSMaxB** [comment]
ok
