### ISSUE TITLE
SIMD optimisation for various algorithms

### ISSUE THREAD

**Issue by adrians** [jedisct1/libsodium#297]
Hi,

I'm thinking of adding SIMD optimisations for arm, x86 and amd64 over the next weeks/months (and profile the new implementations before merging back, to check if they actually improve the performance). BTW, I'm more familiar with using compiler intrinsics than with the inline assembly syntax. Hopefully that's not a problem.

Are these implementations desired? Will they be merged back into the master branch, after passing review?

Thanks,
Adrian S.

**Comment by jedisct1** [comment]
Hi Adrian,

Optimized implementations are definitely welcome and are already on the TODO list.
And using compiler intrinsics over assembly is indeed an excellent thing, if only for readability.

Now, instead of writing these implementations from scratch, take a look at existing ones under a license that allows inclusion on libsodium.

In particular, Floodyberry has carefully written optimized implementations of ChaCha20 and Poly1305 that are worth merging. Supercop also includes optimized implementations of Salsa20 that could be added. Also look at what Cloudflare recently released.

Before tackling the Poly1305 and the stream ciphers, optimized versions of Blake2b is a must, as these will be required for Argon2 support. If you need to start somewhere, I'd suggest starting with this.

Also, SSE2/SSE3/SSE4.1/XOP/AVX versions are great, but the main platform were optimized implementations really matter is ARM. Forget about ARMv6, but NEON-optimized implementations of at least Blake2b, ChaCha20, Salsa20 and Poly1305 would be extremely useful. There is already an excellent NEON implementation of Salsa20 in Supercop. 

Optimized implementations must behave exactly like the existing ones. Which means being free of side channels, but also validating parameters the same way, and handling internal counters overflows exactly the same way.

**Comment by jedisct1** [comment]
For Sandy Bridge architectures, Tung Chou's 25519 implementation is blazing fast:
https://sites.google.com/a/crypto.tw/blueprint/ - http://csrc.nist.gov/groups/ST/ecc-workshop-2015/presentations/session6-chou-tung.pdf

It's mainly written in assembly, but it looks free of side channels, and can be a nice addition.

**Comment by Asmod4n** [comment]
On Apples ARM Chips, Blake2b is faster without NEON optimizations. At least on the A7: https://zerobyte.io/blog/2014/04/29/benchmarking-symmetric-crypto-on-the-apple-a7/

**Comment by jedisct1** [comment]
Waiting for your pull requests :)
