### ISSUE TITLE
Feature request: crypto_generichash_copy()

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium#316]
See also: https://github.com/jedisct1/libsodium-php/issues/64

Use case: Easily calculate intermittent (keyed) hashes of the contents of a stream at regular intervals, which can be useful for detecting race conditions.

[Halite\File](https://github.com/paragonie/halite/blob/master/src/File.php) does something similar using PHP's hash functions (e.g. `hash_copy()`, `hash_update()`) so that, after verifying the MAC at the end of the file, an attacker cannot substitute chunks in the middle of the file without causing decryption to fail.

**Comment by jedisct1** [comment]
Hi Scott,

I can see how that can be required in the PHP bindings, but with the C library, there's nothing more to do than copy the structure. Don't forget that nothing in sodium performs memory allocations except functions that obviously need it (`scrypt`, `sodium_malloc`).

So, states can be freely cloned:

```c
crypto_generichash_state state;
crypto_generichash_state state_copy;

crypto_generichash_init(&state, NULL, 0, 100);
...
state_copy = state;
...
```

`state_copy = state` is all it takes to make `state_copy` a copy of `state`. There are no references inside, since there are no dynamic memory allocations.

Or maybe I misunderstood your needs :)

**Comment by paragonie-scott** [comment]
Perfect. :)
