### ISSUE TITLE
Argon2i integration – Password Hashing API

### ISSUE THREAD

**Issue by mlpo** [jedisct1/libsodium#318]
Argon2, the winner of the Password Hashing Competition was announced a few months ago. I saw the issue #286 and the update of the documentation. So the standard high-level API “will eventually use the […] Argon2i function in its final version.”. It’s great that libsodium offers this feature, since this new hash function presents several interesting functionalities.

Regarding integration, we await for something in particular? Since the winner was officially announced, we had the Argon2 specifications and a research paper which introduces this function. Furthermore, [reference and optimized implementations](https://github.com/khovratovich/Argon2) are available and are maintained.

Is there something that blocks the integration of Argon2i into libsodium?

**Comment by jedisct1** [comment]
The plan to add Argon2 is still on, and the optimized Blake2b implementations were specifically a step towards this. There's still quite a lot of work to do, and it might not be available before libsodium 1.0.8.
There's no need to rush. Argon2 is interesting, but Scrypt is still totally fine.

**Comment by mlpo** [comment]
Yes, I completely agree. Scrypt remains fine. I just wanted to know if we wait a specific event before integration. There are actually no pressing needs. It’s great to know that this functionality will be available.

Anyway, thanks for your reply.

**Comment by jedisct1** [comment]
Hi Mipo,

It takes a little bit more than integration of existing code.

When anything is added to libsodium, it has to work on all supported targets. Which includes Windows, Android, iOS, Javascript, NaCl, QNX, CloudABI, on little and big endian CPUs, on CPUs that require strict alignment, with various compilers including some that can produce broken code or that do not tolerate undefined behaviors some original implementations depend on.

Testing and adapting the code to all the supported platforms is a long and tedious task, but this is  absolutely necessary to keep the portability promise of the library.

libsodium was also specifically designed to be easily packageable. When compiled for Intel CPUs, the resulting binary must work on embedded CPUs without SIMD instructions at all, on CPUs with SSE2 support but nothing else and on recent CPUs where extensions such as AVX can be taken advantage of.
Reference implementations are almost never designed to work that way. A specific flavor is expected to be compiled for a given CPU and is only guaranteed to work on that CPU.
So, they have to be rewritten in order to detect and use the CPU features at runtime instead.
The Argon2 reference and optimized implementations are no exception to this.

We also already have a Blake2b implementation, so importing the one from these implementations wouldn't make sense, especially since they are slower. But, we need to export the round function. Which is one of these things dynamically chosen according to the CPU features. And while that round function has to be shared between two different things, it shouldn't be part of the public API.
To be consistent with other functions used the same way, it should be moved to `crypto_core`. Which means that the existing Blake2b implementation has to be split in half.
These are implementation details, but moving these things around is going to be tricky and take quite some time, especially since the Visual Studio solutions have to be kept in sync.

The Argon2i public API, as exposed in libsodium, has to be consistent with existing code and conventions. Switching from the scrypt to the Argon2i functions should require minimal efforts for users. But we should still expose a low-level Argon2i, that is radically different from the Scrypt one.

Memory allocation functions have to be rewritten, to make the reserved regions properly aligned, protected against swap and core dumps.

Argon2i can use parallelism. Which means threads. Which means that libsodium will require pthreads, or equivalents on other systems. This may not be compatible with the current API, may break existing packages, may make existing implementations slower, and will require a major version bump. And we have to support systems that do not implement threads as well.

Acceptable defaults for interactive and sensitive scenarios have to be determined.

Tests have to be written. They go beyond test vectors. We need to make sure that on no supported platforms, none of the functions read or write an extra byte past or before any allocated buffer. We need to go through manual review, static and dynamic analysis to look for undefined behaviors, and fix them.
We need to make sure that everything works fine even when compiled in an unusual way, such as compiling everything with a C++ compiler, or compiling the C files without using autoconf. Real-world applications and package managers require that.

The documentation has to be written. Which will include examples, and new recommendations on how to choose the parameters.

And as I also maintain these, I will also have to update the Swift, PHP and Javascript wrappers. Recheck that Argon2i works as expected them using these wrappers. On all supported systems. If not, fix the library accordingly. Or the wrappers. Update the docs and examples.

So, as promised, support for Argon2i will be added, and it already started with the Blake2b optimized implementations, which are a prerequisite. But this will require quite a few weekends working full time on it.

**Comment by mlpo** [comment]
Yes, add new features in a library is far from trivial (this is even more true with a critical system, such as cryptography). Even though a feature is already existing, integrate it into such a project is, as you pointed out, a lot of work. When I spoke of “integration”, I was talking about the whole process. You are right to remind that it is not just making a copy-paste of a reference code, especially in a cryptography library with rules, conventions and issues to handle.

The feature will arrive when it arrives, and it's great! My question was about the plans for this new feature, and I'm not surprised that libsodium make it, eventually, available with a level of exigency similar to the rest of the project.

Thank you again for all this work and these details.

**Comment by ranisalt** [comment]
How is the status on Argon2i implementation?

**Comment by jedisct1** [comment]
Argon2i is in the current development code, and will be in the next release.
The high-level `crypto_pwhash()` API is backed by Argon2i.

Feel free to check out the current code in Git and to give it a spin, but avoid this in production yet.

Here is the currently available interface: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_pwhash.h
