### ISSUE TITLE
Question: Memory zeroed before access violation causes crash?

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#325]
When allocating memory with `sodium_malloc` and making it inaccessible via `sodium_mprotect`, does libsodium overwrite the memory with zeroes before finally crashing the application?

I'm concerned about the following scenario: If software using libsodium allows an attacker to force an access violation on pages that have been protected using `sodium_memprotect`, the attacker might then be able to gather information about the content of those pages if they are assigned to the memory space of the attacker or otherwise via some kind of sidechannel attack.

Is this a realistic scenario, and if yes, does libsodium protect against it?

Same for segmentation faults. Are the allocated regions zeroed before crashing?

**Comment by jedisct1** [comment]
Hi Max,

When an application quits, even due to a segmentation fault, the memory pages it uses are reclaimed by the kernel. Memory allocations only reserve virtual memory. When reserved pages of virtual memory are accessed for the first time by a new process, the corresponding physical memory pages are filled with zeros before being visible by the process having performed that allocation.

So, on any operating system with memory protection, a process cannot read data allocated by a previous application, not matter how that application exited.

**Comment by FSMaxB** [comment]
Okay, thank you very much for that explanation. That eliminates one source of paranoia.

**Comment by jedisct1** [comment]
If you use grsecurity, memory pages can also be zeroed right after a process exits, instead of having to wait for them to be reuse. The `PAX_MEMORY_SANITIZE` option controls this.
Also take a look at this: https://github.com/jedisct1/system-tuning-for-crypto

**Comment by FSMaxB** [comment]
Nice, thanks.
