### ISSUE TITLE
Salsa20Random wrongly initialized

### ISSUE THREAD

**Issue by sneves** [jedisct1/libsodium#330]
From `src/libsodium/randombytes/salsa20/randombytes_salsa20_random.c`:

```
typedef struct Salsa20Random_ {
    unsigned char key[crypto_stream_salsa20_KEYBYTES];
    unsigned char rnd32[16U * SALSA20_RANDOM_BLOCK_SIZE];
    uint64_t      nonce;
    size_t        rnd32_outleft;
#ifdef HAVE_GETPID
    pid_t         pid;
#endif
    int           random_data_source_fd;
    int           initialized;
    int           getrandom_available;
} Salsa20Random;

static Salsa20Random stream = {
    SODIUM_C99(.random_data_source_fd =) -1,
    SODIUM_C99(.rnd32_outleft =) (size_t) 0U,
    SODIUM_C99(.initialized =) 0,
    SODIUM_C99(.getrandom_available =) 0
};
```

When `SODIUM_C99` is disabled, i.e., when compiling libsodium as C89 or C++, the above initialization only fills in `key` with the bytes `255, 0, 0, 0, ...`, and every other member—most notably `random_data_source_fd`—is initialized to 0.

**Comment by jedisct1** [comment]
Thanks a lot for spotting and reporting this!
Should be fixed in bc371880d87e597b067b382267211ce6e0fd6658

**Comment by jedisct1** [comment]
Backported to the stable branch.

**Comment by AGWA** [comment]
The use of designated initializers that are gated by conditional compilation seems like a really error-prone programming practice.  It means that field order matters, but a disagreement in order won't be noticed unless `SODIUM_C99` is disabled.  We're lucky that it was `key[0]` which got assigned `-1` and not `initialized`!

I suggest either dropping the designated initializers (since order matters anyways, what value do they add?), or better yet, dropping the struct initializer entirely and letting the struct be zero-initialized.  As long as the code doesn't try to use `random_data_source_fd` if `initialized == 0`, that should be fine.  Then you wouldn't have to worry about field order at all.

**Comment by drbo** [comment]
Does this lead to a vulnerability?

**Comment by jedisct1** [comment]
No.
