### ISSUE TITLE
Support for using X25519 keys to create/verify Ed25519 signatures

### ISSUE THREAD

**Issue by tarcieri** [jedisct1/libsodium#335]
Continuing the third point from #77...

It would be nice if it were possible to use X25519 keys to create and verify Ed25519 signatures.

@trevp has detailed how that could be done in this email:

https://moderncrypto.org/mail-archive/curves/2014/000205.html

**Comment by paragonie-scott** [comment]
This seems pretty neat. How would you design the API for this feature? (Can we call it `crypto_xsign()`? Is that too corny?)

**Comment by tarcieri** [comment]
I noticed @FredericJacobs has a project that does this: https://github.com/FredericJacobs/25519

**Comment by jedisct1** [comment]
GPL, sigh.

**Comment by tarcieri** [comment]
@trevp has just published a specification for this: https://whispersystems.org/docs/specifications/xeddsa/

**Comment by bernedogit** [comment]
I have implemented signatures using X25519 keys. They are based on the Ed25519-donna implementation and the method outlined in https://moderncrypto.org/mail-archive/curves/2015/000376.html. It is available at https://github.com/bernedogit/amber in the files 25519.hpp and 25519.cpp. The functions that implement them are cu25519_sign(), cu25519_verify() and unpack_mx_vartime() functions. Using the direct decompression from Montgomery X to extended Edwards is as fast as decompressing from Edwards Y. Although it is based on the donna implementation it should be easy to adapt it to use the primitives based on the ref10 implementation.

There are two design decisions. The standard Ed25519 signatures compute the hash H(R,A,M) using the Ed25519 public key as A. This ties the message to the public key as explained in https://www.ietf.org/mail-archive/web/cfrg/current/msg07335.html. If we want to keep compatibility with Ed25519 signatures then we still need to cache or compute this key when signing. When decompressing we get the public Ed25519 key for free. We can instead use the public X25519 key as A in the computation of H(R,A,M). This also ties the message to the public key, but it avoids that we must cache or compute the Ed25519 key for signing.

The other decision is where to store the sign bit of the Edwards X coordinate. I have just followed the design of Ed25519 and stored it as bit 255 of the public X25519 key. This is compatible with existing curve25519 DH implementations: they just ignore this bit.

**Comment by trevp** [comment]
Hi Pelayo,

Take a look at XEdDSA, which is a later evolution of that design:

https://whispersystems.org/docs/specifications/xeddsa/

(Though there's still a couple small tweaks I'm going to make to input
validation and the nonce-derivation hashing, which you can see in recent
discussions on curves list).

I have ref10-based code for that, but it would be great to have an
Ed25519-donna option as well.

Trevor

**Comment by bernedogit** [comment]
I have read the XEdDSA discussion in moderncrypto.org. I have implemented the negation of the private scalar in my program. It is in the negate_private_key() function. Using this we can have public keys with the sign bit set to zero.

The Ed25519 specification requires that the private scalars have bit 254 set and the lower 3 bits cleared. This makes the private scalar a multiple of the cofactor. Private scalars obtained by negating a private X25519 key that already includes the masking do not conform to this Ed25519 requirement. From my very limited understanding it seems that this is not a problem for the single signature verification as defined in XEd25519.

Ed25519 also defines batch signature verification. Batch verification is 3 times faster than single signature verification (at least in the ed25519-donna implementation). Therefore there is an incentive for an Ed25519 implementation to use batch verification whenever applicable.  Given that XEd25519 signatures are compatible with Ed25519, can they be used with Ed25519 batch verification? What are the security considerations of not conforming to the bit masking required by Ed25519?

You also proposed in https://moderncrypto.org/mail-archive/curves/2014/000293.html to store the 
sign bit in the signature. The method is otherwise identical to Ed25519, except that it allows the attacker to choose the sign bit. In this proposal all  private scalars comply with the bit masking requirements of Ed25519. How does this scheme compare to XEd25519? It would allow batch verification but it is not clear to me if allowing an attacker to choose the sign bit would somehow offer a practical attack.

**Comment by trevp** [comment]
Hi Pelayo,

Good questions, I'll try to answer them this week.  If you're willing to
post this to curves list, I think the discussion would benefit other people.

Trevor

**Comment by remko** [comment]
Sorry to bump this thread, but has there been any progress on this recently?

**Comment by jedisct1** [comment]
No, but Ed25519 keys can be [converted to X25519 keys](https://download.libsodium.org/doc/advanced/ed25519-curve25519.html).

**Comment by remko** [comment]
> No, but Ed25519 keys can be converted to X25519 keys.

Understood, thanks. But it's actually the other way round I'm interested in.

Is anyone still working on this? And is there still interest in adding this functionality to libsodium?

**Comment by Shokodemon** [comment]
trying to implement omemo with libsodium using the ed25519 conversion does break the process. ed25519 public part doesn't play nice with curve25519 public part, sadly.

**Comment by sdgathman** [comment]
I had cjdns working with libsodium through v19.  Now, cjdns has implemented its own unification using its embedded copy of nacl.  The key function that has no equivalent in libsodium is:

```
void Sign_signingKeyPairFromCurve25519(uint8_t keypairOut[64], uint8_t secretCryptoKey[32])
{
    Bits_memcpy(keypairOut, secretCryptoKey, 32);
    keypairOut[0] &= 248;
    keypairOut[31] &= 63;
    keypairOut[31] |= 64;
    ge_p3 A;
    ge_scalarmult_base(&A, keypairOut);
    ge_p3_tobytes(&keypairOut[32], &A);
}
```

Seems simple enough, but the ge_ functions are not exported from libsodium.

**Comment by tarcieri** [comment]
@sdgathman that's not really a `signingKeyPairFromCurve25519` function: it's simply computing an Ed25519 public point from a private scalar. You just so happen to be using the same scalar for X25519 as you are for Ed25519. If nothing else, it's poorly named.

But there is one issue with this code in regard to the contract of the NaCl API: in NaCl, the canonical scalar is "unclamped" (i.e. the various setting and clearing of bits in the scalar, to clear the cofactor and ensure the scalar is within the group order). That is to say, ordinarily the "clamping" occurs prior to a private scalar operation, and the canonical scalar is stored without the bits being set/cleared.

This probably won't be a practical problem, but it is a deviation from the way the rest of NaCl implementations operate.

**Comment by sdgathman** [comment]
As a packager, I could use https://github.com/jedisct1/libsodium/issues/236 instead, and it would be even easier.  I could use the upstream code largely as is with maybe simple function name mapping.

**Comment by Shokodemon** [comment]
@tarcieri Im sure the ''fix'' can be localized to XEdDSA/Aligator, without affecting NACL as a whole? i sadly lack the mathematical background to touch this code, but would really love having this. i have a few projects planned that can use this/rely on this.

**Comment by jedisct1** [comment]
@sdgathman #236 is done (`scalarmult_ed25519()`, `scalarmult_ed25519_base()`).

**Comment by sdgathman** [comment]
@jedisct1 - now I have a way forward.  I'll map to libnacl until the changes to libsodium hit Fedora.
