### ISSUE TITLE
Support for associated data with long nonce

### ISSUE THREAD

**Issue by drbo** [jedisct1/libsodium#336]
Libsodium currently supports AEAD with a 96-bit nonce, and authenticated encryption with a 192-bit nonce but no associated data.  It would be nice to support both the longer nonce and associated data in the same function.

This is not critical, but would be useful in some cases.

**Comment by jedisct1** [comment]
There are indeed quite a few cases where a longer nonce would make things easier.

But rather than providing yet another variant of the current and future AEAD constructions, the plan is to:
1) Add a high-level API for key exchange
2) Add a generic API to derive a subkey and a nonce from a key and a longer nonce

**Comment by drbo** [comment]
That makes sense.  It will be very nice when I can leave the nonce out of the API and implicitly generate it every time.
