### ISSUE TITLE
Feature request: sodium_realloc

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#337]
libsodium currently has `sodium_malloc`. This is a really slow operation and it reserves much more memory than what was actually requested.

Providing a `sodium_realloc` function would drastically increase the performance of workloads that need to enlarge an allocated region.

As I understand it, one page of memory is usually about 4k big and `sodium_malloc` reserves at least 3 of them, one to actually store data. So every `sodium_realloc` thats less than 4k should be quite a cheap operation, shouldn't it?

**Comment by jedisct1** [comment]
Hi Max,

What is your use case for `sodium_realloc()`?

These functions were mainly designed to store keys, whose size is fixed.

`sodium_realloc()` is tricky to implement, especially since we try to keep the region close to the upper page, and not to the base page. When shrinking a region, the base pages need to be made inaccessible, and new ones will have to contain the metadata and be reprotected. And no matter what the operation is, we need to unlock pages in order to recompute the size and offsets, and relock them afterwards. I'm not sure that the end result would be a drastic increase in performance.
I'm also not sure about what the interactions with previous calls to `sodium_mprotect_*()`  should be in case of a reallocation.
If only to avoid introducing tricky code for use cases that are not very common, I'd rather recommend just using a new allocation + memcpy() instead.

**Comment by FSMaxB** [comment]
My use case is to serialize the internal state of my library that contains private keys. But it's quite hard to know in advance how much memory is going to be needed.

I guess I made incorrect assumptions about the inner workings of `sodium_malloc`, this seems much more complicated than I thought.

If implementing a `sodium_realloc` is not feasible, the approach I would take would be to always allocate as much memory as is available in the pages that `sodium_malloc` already reserves. This won't protect me from cases where I read/write out of bounds at the end of the region I'm using, but it would bring all of the other niceties that `sodium_malloc` provides without adding the overhead  of having to do a complete `sodium_malloc` whenever more space is needed.

Is there a way to reliably find out the amount of memory I can allocate with `sodium_malloc` before it starts using a second memory page for the data?

**Comment by jedisct1** [comment]
There is a 16 bytes canary, so `page_size - 16`.
Instead of allocating `size` bytes, you can allocate up to `((size + 16 + (page_size - 1)) & ~(page_size -1)) - 16` bytes for the same number of pages.

**Comment by FSMaxB** [comment]
Great. Thanks!
