### ISSUE TITLE
Windows installation through Cygwin + MINGW64 hangs

### ISSUE THREAD

**Issue by DJDavid98** [jedisct1/libsodium#357]
I'm trying to set this up on my Windows development machine, so far no luck. The PECL package can't even be found

![](http://i.imgur.com/LrQgvkk.png)

and even if that wasn't an issue, running the commands at the top of [this page](https://download.libsodium.org/doc/installation/index.html) in MINGW64 ends up hanging here:

![](https://cloud.githubusercontent.com/assets/3200580/13187601/62b2aca6-d74c-11e5-976b-c534ef54801f.png)

I have no idea what to do at this point. I can't move to Linux as I use a lot of programs that don't work or don't have alternatives there. If I can't set this up here in Windows, I'm probably going to have to ditch using `libsodium` altogether. Do you have anything that could potentially help with the installation process?

**Comment by jedisct1** [comment]
I've never used PHP on Windows, and there might be some issues with libsodium-php that prevents it from being present in PECL on this platform.

However, [the PHP documentation](https://wiki.php.net/internals/windows/stepbystepbuild#building_pecl_extensions) says:

    PHP officially supports building with Microsoft's Visual C++ compilers. MinGW and other compilers are NOT supported or even known to work.

libsodium itself shouln't be an issue, and you can just grab the precompiled DLLs.
But the PHP extension, or probably just the `config.w32` file, might require some tweaks. Give it a try! Help would be definitely appreciated in order to ensure that the PHP extensions works out of the box on Windows.

**Comment by DJDavid98** [comment]
I can't really _give anything a try_ as I honestly have no idea about the magic behind this extension. I just saw libsodium mentioned online and thought I'd try using it in my PHP project, but so far it's been nothing but roadblocks. I could only set it up on my Linux VPS, but if i can't develop my app locally because of it's absence, using it simply isn't an option.

**Comment by jedisct1** [comment]
There is no magic behind it; it's a pretty boring PHP extension written like most other PHP extensions.
But nobody tried to see why it didn't compile (if that's the actual issue) on Windows yet. The required changes are probably simple, but they haven't been done yet, and I don't even know how to install PHP on Windows.

If using Linux or BSD is not an option, I'm awfully sorry, you won't be able to use this extension for now.

**Comment by DJDavid98** [comment]
Understandable. If you ever want to install PHP on Windows, the easiest way would probably be through [XAMPP](http://apachefriends.org/) which also installs Apache, MySQL, and some other related tools.

**Comment by jedisct1** [comment]
Closing here, as this is a libsodium-php question.
