### ISSUE TITLE
Nonce-misuse-resistant authenticated encryption

### ISSUE THREAD

**Issue by DemiMarie** [jedisct1/libsodium#361]
Some devices (mostly embedded) have neither a good source of entropy nor a good way to store a persistent counter.  This makes the existing APIs in libsodium unsuitable.

While a good entropy source is mandatory for key _generation_, I suspect that many of these devices have keys that are programmed into the device at a central location, and generated externally.  However, the inability to store a counter means that the existing APIs &ndash; all nonce-based &ndash; cannot be used (easily) used securely.

This problem can be solved by providing nonce-misuse-resistant APIs, which trade performance for resistance to nonce reuse.  In this context, "nonce-misuse-resistance" means _full_ resistance: a two-pass scheme in which the _only_ information leaked from nonce reuse is whether the message repeated, and even that only if the AAD repeats.  This implies a two-pass, offline scheme &ndash; but the existing APIs are already offline, and so a two-pass scheme would not make for a very different API.

Additionally, nonce-based algorithms are somewhat easy to misuse.  It would be nice, and IMO very much in the spirit of libsodium, to provide algorithms that give users less rope to hang themselves.

**Comment by paragonie-scott** [comment]
> Some devices (mostly embedded) have neither a good source of entropy nor a good way to store a persistent counter.

Not having a good way to store a persistent counter sounds like a problem with the device.

> This problem can be solved by providing nonce-misuse-resistant APIs, which trade performance for resistance to nonce reuse.

Which ones would you propose specifically?

**Comment by drbo** [comment]
#### NOTE: I am just a programmer (not a cryptographer), so please don't assume that I know what I am talking about.  That said, all claims that I make are true to the best of my (limited) knowledge.

> > Some devices (mostly embedded) have neither a good source of entropy nor a good way to store a
> > persistent counter.

> Not having a good way to store a persistent counter sounds like a problem with the device.

The big issue is race conditions.  If you could lose power at any time, the only way to safely store a persistent counter is to ensure that data is committed to nonvolatile memory between the time the new nonce is committed and the time the actual encryption/decryption is performed.  This is slow and prevents writes from being batched.  It also wastes power.

> > This problem can be solved by providing nonce-misuse-resistant APIs, which trade performance for 
> > resistance to nonce reuse.

> Which ones would you propose specifically?


Something similar to [this paper][1], but with ChaCha20 and Poly1305 (and possibly Blake2b) instead of AES and GCM.

There may be some difficulties (the ChaCha20 nonce is only 64 bits, which is too short for the construction given and a reasonable number of messages; also, the construction in the paper loses security rapidly as the number of messages sent increases), but I think this can be solved by either of these options, both based on "hiding" the standard ChaCha20/Poly1305 (nonce-based) MAC:

1. Use a block cipher in ECB mode to hide the MAC, and XSalsa20 as the stream cipher.
2. Use HSalsa20 to expand the 128-bit MAC to 256 bits and randomize it (producing the auth tag), then use Blake2b to compute the ChaCha20 key from the auth tag and the main key; I **believe** that this is secure assuming that Blake2b is a PRF or (Blake2b is collision-resistant and ChaCha20 resists related-key attacks) (I understand that both of these assumptions are considered true).

I have written code that implements the latter option using primitives already in libsodium, but before it could be included it would need to be reviewed by someone with more experience in crypto than I.

[1]: https://eprint.iacr.org/2015/102.pdf

**Comment by jedisct1** [comment]
Having a nonce-misuse-resistant scheme would be nice, and you described a perfect use case for it.

Before introducing a new construction, we have to consider a few things:
1) Security
2) Speed on the main platforms it will be used on
3) Interoperability with other crypto libraries

AEZ, AES-SIV and HS1-SIV are better candidates than a new construction. If the main target is embedded systems without hardware support for AES, HS1-SIV is probably the way to go.

The outcome of the CAESAR competition will influence this, but I also suspect that HS1-SIV is more likely to be implemented in different crypto libraries than other current proposals.

**Comment by drbo** [comment]
AES-SIV is unnecessarily slow, due to using (non-parallelizable) CMAC.  AES-GCM-SIV was shown to be over 5 times faster (on Haswell/Broadwell) and provably secure [here][1].

I suspect that AES-SIV is in fact so slow that there is no point including it &ndash; even on chips with hardware AES it suspect it will be slower than (optimized) HS1-SIV, whereas AES-GCM-SIV is less than 20% slower than AES-GCM.

[1]: https://eprint.iacr.org/2015/102.pdf

**Comment by jedisct1** [comment]
I was referring to AES-GCM-SIV. 20% slower than AES-GCM means insanely slow without hardware support, and tricky to implement in a portable way, and without side channels.

HS1-SIV is way easier to implement safely, and is likely to offer decent performance on all processors.

**Comment by drbo** [comment]
Ah okay!

It might be a good idea to offer both.  Libsodium already has machinery for AES256-GCM, and does offer it on supported processors due to its speed when hardware accelerated.

**Comment by paragonie-scott** [comment]
Sadly, HS1-SIV didn't make it to round three of CAESAR.

Of the remainining NMR candidates, AEZ looks good (though I personally favor NORX's strategy of 256-bit random nonces).

**Comment by jedisct1** [comment]
Closing this for now, waiting for the outcome of the CAESAR comp, and there is a plan to include a function to generate safe nonces until then.

**Comment by jedisct1** [comment]
All constructions recently got a `keygen()` function.

The plan is to also implement a `noncegen()` function that returns a safe nonce according to a key, a message, and a context. And for constructions with a short nonce, `noncegen()` will return a subkey in addition to the nonce.
