### ISSUE TITLE
Inconsistent function parameters

### ISSUE THREAD

**Issue by ranisalt** [jedisct1/libsodium#383]
Currently, I'm trying to use `crypto_generichash` and `crypto_pwhash_str_verify` on a project, but those functions have wildly varying parameter typing:

- `generichash` takes an `unsigned char*` input, while `pwhash_str_verify` takes a `char*`
- `generichash` and `pwhash` output to `unsigned char*` but, oddly enough, `pwhash_str` outputs to `char[]`
- `outlen` and `passwdlen`, both representing sizes, on `pwhash`, are `unsigned long long`, but `memlimit` is `size_t` (types are probably swapped here)
- `outlen` on `generichash` is received as `const` (which is good), but it is not on `pwhash`

Could the API be more consistent, receiving the same types for when parameters mean the same thing?

I mean, I can't easily change from `generichash` to `pwhash` without a lot of casting, especially on C++ with a f*ckload of casting stuff and using `std::string` using `char` internally:

![http://imgur.com/ar7z8IE](http://i.imgur.com/ar7z8IE.png)

*ps: it would be very nice to have a `generichash_str` function assuming the input is null-terminated and output is a correct-sized array, just like `pwhash_str`.

**Comment by jedisct1** [comment]
Hi Ranieri,

The API tries to be quite consistent, and the main conventions are documented here: [internals](https://download.libsodium.org/doc/internals/index.html).

Vectors of bytes are represented as `unsigned char *` pointers.
C strings as `char *`.

Vectors of bytes (for example: keys) may not be valid strings. In particular, they may contain sequences that cannot be decoded as valid UTF-8 characters. This is binary data, which is not supposed to be printed without extra encoding.

`generichash` and `pwhash` serve very different purposes.

The former computes a hash on a vector of bytes. This can be the content of a `.jpeg` file. This is not something you can print as a string.

The later hashes a password. And a password is usually a string.

`pwhash()` returns a vector of bytes. The purpose is to use it as a key. Once again, these bytes may not represent a valid string.
`pwhash_str()` returns a string, which is the `pwhash()` output encoded as a string, so that it can be stored in a database or in a text file. It is guaranteed to be a valid, zero-terminated C string, with only ASCII characters.

If you feel like you need to cast types, you may not be using a function correctly. With the exception of passwords-related functions and hexadecimal-from/to-binary conversion functions, everything in the library operates on binary data, not strings.

**Comment by ranisalt** [comment]
Great explanation that I was really missing. Now it's clear and I feel my issue is stupid :laughing: thanks and keep up the good work!
