### ISSUE TITLE
AES-GCM is relatively slow (just over 1/2 speed of OpenSSL)

### ISSUE THREAD

**Issue by drbo** [jedisct1/libsodium#388]
Libsodium's AES-GCM implementation encrypts at ~1.4GB/s and decrypts at ~1.2GB/s.  OpenSSL gets ~2.6GB/s for encryption.

**Comment by paragonie-scott** [comment]
Is this related to, say, #358 (or other optimizations that aren't currently implemented)? Or is there something in libsodium incurring a performance penalty?

**Comment by jedisct1** [comment]
What platform is that on? What block size? I get about 10 Gb/s on my Macbook (i7 2.8Ghz), using [this benchmark](https://gist.github.com/jedisct1/63a4df48c7b367b45664ea0a9f5c1d4e). 

There is still room for optimizations for sure, especially since we use a pure C implementation (with intrinsics). You can squish some CPU cycles by compiling with `--enable-opt`.

**Comment by jedisct1** [comment]
GHash was implemented according to the original Intel's paper from 2010.

[New techniques](https://crypto.stanford.edu/RealWorldCrypto/slides/gueron.pdf) for fast multiplication in finite fields have been published since, and perform better on modern Intel CPUs.

The libsodium implementation will eventually be updated to use montgomery reduction.

No ETA, as the current implementation is already fast enough for most applications, but the roadmap has been updated to reflect this.

**Comment by jedisct1** [comment]
The original patch sent by Intel to the OpenSSL project includes this statement:
```
## LICENSE:                                                                   ##
## This submission to OpenSSL is to be made available under the OpenSSL       ##
## license, and only to the OpenSSL project, in order to allow integration    ##
## into the publicly distributed code.                                        ##
## The use of this code, or portions of this code, or concepts embedded in    ##
## this code, or modification of this code and/or algorithm(s) in it, or the  ##
## use of this code for any other purpose than stated above, requires special ##
## licensing.                                                                 ##
```

Gueron's paper on fast GHASH computations was not released, and this contribution forbids using `concepts embedded in this code`.

That is quite a problem.

**Comment by FSMaxB** [comment]
Isn't this a self contradiction? How can something be available under the OpenSSL license and still be restricted in that way?
