### ISSUE TITLE
crypto_secretbox with automatic nonce

### ISSUE THREAD

**Issue by lvh** [jedisct1/libsodium#392]
XSalsa20, the underlying primitive, has 24 bytes worth of nonce specifically so that nonces can be selected randomly with negligible probability of collision. libsodium already has the awesome `crypto_easy` so I don't have to worry about _some_ stuff, but nonces are still up to me. I don't know if there's a particular standard for nonces (perhaps prepending or appending), but it'd be great if there was an API where I didn't have to worry about the nonce either.

I'm open for suggestions on deterministic nonces vs randomized ones, but it'd be great if application authors had the option of not thinking about that at all.

**Comment by lvh** [comment]
I am potentially interested in producing a deterministic nonce scheme that generichashes/blake2bs (for personalization) to produce the nonce. This would accidentally also solve #361 (I think) by just taking nonces out of the equation.

**Comment by paragonie-scott** [comment]
> but nonces are still up to me

While I agree with the idea that *developers shouldn't be responsible for nonces*, this is generally something solved in higher-level implementations ([for example](https://github.com/paragonie/halite/blob/ac89eee5e20295a3c7ed39a021132022f4863e0b/src/Symmetric/Crypto.php#L95-L149)).

> I don't know if there's a particular standard for nonces (perhaps prepending or appending), but it'd be great if there was an API where I didn't have to worry about the nonce either.

Prepending the nonce is fine:

```php
/**
 * Encrypt a message
 * 
 * @param string $message - message to encrypt
 * @param string $key - encryption key
 * @return string
 */
function safeEncrypt($message, $key)
{
    $nonce = \Sodium\randombytes_buf(
        \Sodium\CRYPTO_SECRETBOX_NONCEBYTES
    );

    $cipher = base64_encode(
        $nonce.
        \Sodium\crypto_secretbox(
            $message,
            $nonce,
            $key
        )
    );
    \Sodium\memzero($message);
    \Sodium\memzero($key);
    return $cipher;
}

/**
 * Decrypt a message
 * 
 * @param string $encrypted - message encrypted with safeEncrypt()
 * @param string $key - encryption key
 * @return string
 */
function safeDecrypt($encrypted, $key)
{   
    $decoded = base64_decode($encrypted);
    if ($decoded === false) {
        throw new \Exception('Scream bloody murder, the encoding failed');
    }
    if (mb_strlen($decoded, '8bit') < (\Sodium\CRYPTO_SECRETBOX_NONCEBYTES + \Sodium\CRYPTO_SECRETBOX_MACBYTES)) {
        throw new \Exception('Scream bloody murder, the message was truncated');
    }
    $nonce = mb_substr($decoded, 0, \Sodium\CRYPTO_SECRETBOX_NONCEBYTES, '8bit');
    $ciphertext = mb_substr($decoded, \Sodium\CRYPTO_SECRETBOX_NONCEBYTES, null, '8bit');

    $plain = \Sodium\crypto_secretbox_open(
        $ciphertext,
        $nonce,
        $key
    );
    if ($plain === false) {
         throw new \Exception('Scream bloody murder, the message was tampered with in transit');
    }
    \Sodium\memzero($ciphertext);
    \Sodium\memzero($key);
    return $plain;
}
```

Even if an attacker tries to tamper with the first 24 bytes, all they can succeed in doing is making the Poly1305 authentication tag fail.

> I am potentially interested in producing a deterministic nonce scheme that generichashes/blake2bs (for personalization) to produce the nonce.

How would you generate it?
* A keyed and/or personalized BLAKE2b hash of the plaintext?
* Using CMAC to replicate SIV mode?

Writing an opaque higher-level wrapper in `$languageOfChoice` that abstracts the nonce concern away from the end user is my preferred way to address this concern. But in fairness, I don't delve into embedded devices at all, so I'm not sure what the correct and appropriate solution would be for that realm.

**Comment by lvh** [comment]
I'm a cryptographer, so I'm familiar with secure constructions you can use here. In that sentence, "me" was me the hypothetical libsodium/libsodium-binding user. That might accidentally be me, because I write software where I wish I didn't have to think about the nonce. Just I don't have to worry about having a secure authenticated encryption construct, even though I could compose one if I had to 😄 

My comment about prepending/appending was not about what is secure, but about what is an existing standard, so that we can be compatible with existing software. Thank you for your link to halite; pending other bindings doing something similar that gives us a suggestion for an implementation choice.

You mention that you prefer handling this in a wrapper, but I don't understand why that's preferable:

* There is evidently more than one way to do this, and I think it's non-trivial for many of the users of libsodium to do this correctly themselves.
* This feature is currently not available in most libsodium bindings, and adding that *n* times is a lot harder than adding a few new functions to each libsodium binding.
* It's tricky to do there even for the subset of users that write bindings, especially if you care about implementation properties like zero-copy (trivial to do for libsodium, tricky to do in many languages that have bindings to it; the other Clojure library currently does not do this and neither do the released versions of the Java bindings).
* There is a lot of interop value in having a single standard.
* Many current APIs are strictly convenience APIs. For example, having both one-shot and precomutation APIs, which are "unnecessary" but also probably the most commonly used API.
* There are also people using libsodium directly from C and C++, and those people should also get a nice API.
* Finally, assuming that we pick the "obvious" choice (more on that later), implementing in libsodium what other bindings may already do in a high-level binding doesn't limit their capabilities. At worst, you get to delete some code and replace it with a C call that probably has better properties.
* Even before adding deterministic nonces, a nonceless decryption API that assumes a prepended nonce would still simplify a lot of software (anything that doesn't acquire the nonce out of band, AFAICT).

I'd argue that nonces can be a footgun and should be avoided if possible, but it appears we're in agreement there 😄 

I think `nonce || ctext` is the obvious choice. Given what's currently in libsodium, I think keyed BLAKE2b is also the obvious choice. I'd prefer to use it with a personalization, because you never know what else people might be doing with that construction, but I could live with regular generichash. (`libsodium nonce` is a mere 1 byte away from being 16 bytes long!)

This issue was precipitated by a friend (an experienced cryptographic engineer) mentioning that he liked  libsodium, but he wished there was an API that would just take care of the nonce already. I remember thinking that before, hearing that complaint before from other people, and especially in some software I've been writing recently, I'm pretty sure they're right 😄

**Comment by paragonie-scott** [comment]
> I'm a cryptographer, so I'm familiar with secure constructions you can use here.

I was hoping to hear more about what you had in mind for the deterministic salt. Sorry if my questions came across wrong. This is a topic that greatly interests me as well.

> My comment about prepending/appending was not about what is secure, but about what is an existing standard, so that we can be compatible with existing software.

Okay, I can sort of answer that from the projects I've worked on:

* CakePHP: `MAC || iv || ciphertext` (AES-CBC)
* CodeIgniter v3: `MAC || iv || ciphertext` (AES-CBC by default)
* Defuse v1: `MAC || iv || ciphertext` (AES-CBC)
* Defuse v2: `Version || HKDF-salt || nonce || ciphertext || MAC` (AES-CTR)
* Halite: `Version || HKDF-salt || nonce || ciphertext || MAC`
* Laravel Encrypter: JSON: `{"iv", "value", "mac"}` (AES-CBC) (*sigh*)
* RNCRyptor: `Version || other metadata || IV || ciphertext || MAC` (AES-CBC / AES-CTR)

It varies, but IV/nonce before ciphertext seems to be the general pattern most people follow. The inconsistency seems to be mostly "prepend or append the MAC?" but IIRC all of the libsodium constructions append it.

**Comment by lvh** [comment]
No problem; I just didn't understand why you preferred a binding-level solution (or just generally not doing this in libsodium) -- but it appears that was a misunderstanding?

Anyway, that's a lot of AES-CBC :D I was mostly hoping for accidental compatibility (that is to say: the thing libsodium does is something some library previously did by itself), so that means halite is the really interesting one here. How does the HKDF-salt work?

Since an implementation probably says 1000 words, I'll write one for caeisum. Incidentally, for caesium it was a lot easier to _append_ the nonce (mostly because I didn't feel like messing around with java.nio.ByteBuffer or buffy). (I still think we should prepend here; that's just an incidental consequence of the APIs I have in caesium and the byte array copy tools available in Java)

**Comment by paragonie-scott** [comment]
> How does the HKDF-salt work?

During encryption: In addition to 24 random bytes being generated for the Xsalsa20 nonce, an additional 32 bytes salt is generated. This is used for the splitting the user's key (using HKDF-BLAKE2b instead of HKDF-HMAC-*) into two keys: one for encryption, one for authentication. The salt is included in the MAC calculation.

During decryption: The salt is used to re-split the keys.

All a user has to type is:

```php
$ciphertext = SymmetricCrypto::encrypt($string, $encryptionKey);
$plaintext = SymmetricCrypto::decrypt($ciphertext, $encryptionKey);
```

...since these details are totally abstracted away from them. Even if a birthday collision occurs with the random nonce (birthday of 2^96, so very unlikely), unless the salt also collides (both colliding indicates a broken RNG), you'll virtually never (birthday of 2^224) use the same `(nonce, key)` pair.

**Comment by lvh** [comment]
So, if I understand correctly, Halite's encrypt/decrypt doesn't use secretbox, but composes an AE scheme out of Poly1305 and XSalsa20 manually?

**Comment by lvh** [comment]
I added a sample implementation in the reffed commit (with appended nonce instead of prepended nonce because that was accidentally easier). What I'm suggesting for libsodium is to have the nonce prepended for consistency.

@jedisct1 I'm volunteering to implement this unless you think it's a horribly bad idea :)

**Comment by lvh** [comment]
(I'm going to do a little more formal analysis before I start claiming this is fine, though.)

**Comment by lvh** [comment]
@paragonie-scott: I have some more questions about the above scheme:

1. Why HKDF-BLAKE2b instead of just BLAKE2b?
2. I'm assuming the salt is passed to HKDF as the salt?
3. Cryptographically speaking, what is the semantic difference in your design between the salt and just having a huge (deterministic) nonce?

**Comment by jedisct1** [comment]
To be honest, and I'm not convinced that it would be a worthy addition.

There are many scenarios where the user needs full control over the nonce.
Some protocols use nonces composed of one half chosen by the server, and the other half chosen by the client. Other protocols needs to use counters or monotonically increasing timestamps in order to prevent replay attacks. Some applications may require a tweakable cipher in the traditional sense, with a deterministic nonce.

Speaking of deterministic nonces, they are okay for signatures, but a terrible idea as a default for multiple encryptions with a single key. You don't want attackers to spot repeated messages, and even with MR schemes, that requires non-deterministic nonces.

The `crypto_box` API already has many functions to achieve the same thing. Adding even more could cause more confusion than solve actual problems. Real-world applications have no problems using `sodium_random()` to generate the nonce, and storing it in the best possible way for the given application.
An API overhaul is likely to happen in a major revision of the library, and that would be a good opportunity to revisit this. But I don't think that adding even more APIs to still do the same thing is good.

And for consistency, this can't just be done for `crypto_box`, but also for the AEAD constructions. Whose nonces are too small to be randomly generated.

My initial plan was quite different provide a real key exchange API. That returns a set of ephemeral shared keys, and initial nonces. These nonces can then be safely incremented after each message. Applications can decide whether they need to store them along with the message or not. The same API will make rekeying easy. And can be used with all the currently available and future constructions.

**Comment by jedisct1** [comment]
You prefer the nonce after the ciphertext. Scott prefers the nonce before. Someone else will need  an algorithm identifier and a version number in addition to a variable-sized nonce. For Minisign, I'd need a key identifier in addition to that. For DNSCrypt, I only need to store truncated nonces.

We can't provide APIs to solve all these situations. That end result would be confusing and still not a good fit for many use cases. The core library should stay generic and focus on providing the crypto primitives, not on protocols implementation.
Which doesn't mean that bindings cannot go one step further and provides extra functionalities or make usage more idiomatic.

**Comment by lvh** [comment]
I'm sorry to hear you feel that way. I'll try to address your comments individually.

If your comment about where *I* want the nonce are about the sample I posted: I have no preference where the nonce goes. Your point about some protocols already having a fine solution for nonces is well-taken, but I'm not trying to solve their problem; I’m trying to solve for the case of someone who just wants to use a key to encrypt some data.

You're right that existing software has found solutions for this, but you're selecting from software that ended up using libsodium. Therefore, your argument about existing software is vulnerable to selection bias. This problem is particularly noticeable for stores for data at rest, especially distributed and eventually consistent ones (where nonces must be randomized because you can't acchieve consensus between peers). I know of 2 pieces of software from my team in the last 6 months that ended up using Fernet instead, and one of the main reasons was not having to think about nonces. Implementors did not feel comfortable doing string munging and splitting because they have no idea of the security properties that has. That seems like a good reflex, not something I want to discourage, even if they may have accidentally gotten it right. I would have preferred them to end up using libsodium. That is an argument for having an API that takes care of nonces, regardless of whether or not it's deterministic or NMR or purely randomly nonce. The presence of such APIs in some (but not all bindings), also seems to point in that direction.

I do not understand why making this a binding level concern improves matters, for the reasons I've already laid out. It seems doing it in bindings would have strictly more downsides than doing it in libsodium. If more functions here are simply unacceptable because there are too many, that should similarly affect bindings.

Deterministic encryption does result in deterministic ciphertexts. I'm not sure I agree that's necessarily so bad. That is indeed a failure mode of NMR schemes, but it's a better failure mode than plaintext disclosure. In some schemes, this can be a desirable property. If that detection is possible, then it's not a huge leap to consider replay attacks in scope for that protocol. Since recipients storing all nonces they’ve seen before is impractical, such protocols typically come with time stamp validity. That fixes the determinism problem too. This is better than using time stamps as nonces directly: it uses BLAKE2b to "smear" the time stamp across the nonce space, meaning you don't have to worry about the ideal time resolution to use. It also has the subtle benefit of hiding the time stamp, although that doesn't matter for most online protocols.

Putting my cryptographer hat on: 256 bits of entropy should be enough for everybody ;)

It seems like there are two main objections that I want to separate:

* these namespaces have too many things already
* deterministic nonces suck

Would you consider a prefix-nonce *decryption* for box & secretbox? If so, at least that provides clear guidance for bindings implementing NMR/deterministic nonce how to design it. If yes, would you consider a randomized-prefix-nonce encryption API for box & secretbox? Alternatively, would you consider an NMR scheme for secretbox/box? The case for NMR being useful seems more clear, since that's already been requested in a different issue.

**Comment by lvh** [comment]
(Something I forgot to add before: the notion that deterministic encryption can be a good thing of course only illustrates your point that you can't please everyone :))

**Comment by lvh** [comment]
After thinking about it a bit more, I agree that an NMR scheme might be noisy, so I'll retract my suggestion to implement it. I'll keep my offer to implement decryption with prefix nonce, and encryption with randomized prefix nonce. Per your suggestion, I will implement the deterministic and NMR schemes in my binding and see where it goes from there.  Thanks for your thoughtful comments :)

**Comment by jedisct1** [comment]
Deterministic nonces have valid uses. But they are a regression over the current API (when used correctly). Eavesdropper being able to learn about repeated messages may totally destroy the security guarantees of existing applications if they switch from the current API to the once producing deterministic nonces.
Having such an API would be good if there was no easy way to compute deterministic nonces, but this is not the case. And for the vast majority of actual use cases, non-deterministic nonces are preferable.

This is how a prefix-nonce API would be implemented for `crypto_box`:
```c
    randombytes_buf(nc, 24);
    return crypto_box_easy(nc + 24, m, mlen, nc, pk, sk);
```
and for `crypto_box_open`:
```
    return clen < 24 ? -1 : crypto_box_open_easy(m, c + 24, clen, n, pk, sk);
```

That's one of two trivial lines of code. So if we do it for
- `crypto_box`
- `crypto_box_open`

That has to be done for the precomputed API as well:
- `crypto_box_afternm`
- `crypto_box_open_afternm`

And `secretbox`:
- `crypto_secretbox`
- `crypto_secretbox_open`

And if we add an algorithm identifier, we will need to add new constants and functions to access and verify them.

Right after this has been done for `crypto_box` and `secretbox`, people will ask why this doesn't exist for AEAD constructions.

Some future AEAD constructions may provide a nonce long enough. But with the currently available ones, we have a problem. At best, we would need a different API that also returns a key. Things would get really inconsistent.

The API getting bigger and bigger without providing anything new makes me sad. It starts smelling like bloat, and gets confusing to newcomers. Each new version remains backwards-compatible and retains NaCl compatibility. Which is both a good thing and a drag.
I am suggesting that bindings implement different, better, closer to protocols APIs, so that we can learn from them and from how people use them. And eventually build libsodium 2 based on these experiences.

In the meantime, keeping piling more and more ways to use the same primitive is not great.

But as you said, it would be really good to have a common, or at least a recommended way to encode nonces and ciphertexts, if only for interoperability purposes.

I would suggest specifying this in the documentation, along with providing example source code.

**Comment by jedisct1** [comment]
This will have to wait libsodium2, which will get away with the NaCl API and use something closer to the libhydrogen API instead.
