### ISSUE TITLE
[runtimejs] undefined reference to 'crypto_scalarmult_curve25519'

### ISSUE THREAD

**Issue by facekapow** [jedisct1/libsodium#411]
Hi there, I'm working on a project that uses libsodium, and it compiled fine, until I had to generate keypair. When I used `crypto_box_keypair`, the linker started throwing up errors about undefined references to `crypto_scalarmult_curve25519_*`. And looking through the source, the linker was right. `crypto_scalarmult_curve25519` and `crypto_scalarmult_curve25519_base` are never implemented, only declared in `crypto_scalarmult_curve25519.h`. *Are* they implemented anywhere?

**Comment by jedisct1** [comment]
Hi there!

These functions are certainly defined :)

Where did you get the source code from?
How did you compile it?

**Comment by facekapow** [comment]
1) It was pulled into the [project's deps folder](https://github.com/runtimejs/runtime/tree/add-libsodium/deps)
2) With an x86_64 cross compiler

Also, could you tell me where they are defined just to check in my version of the source if it's there?
Thanks for the quick response, by the way.

**Comment by paragonie-scott** [comment]
Hello,

> 2) With an x86_64 cross compiler

Could you be a little more specific? Thanks :)

**Comment by facekapow** [comment]
Built with [these steps](https://github.com/runtimejs/runtime/wiki/Build)

**Comment by jedisct1** [comment]
Your project seems to include a copy of libsodium 1.0.3. Did the issue appear when you copied files from version 1.0.13 or from the current `stable` branch over this copy?

The file structure changed quite a bit since 1.0.3, so if you didn't pull the `stable` branch, or the files from a tarball, you need to clean your object directories, and run `./autogen.sh` to rebuild the `configure` script and the Makefiles.

**Comment by jedisct1** [comment]
Looks like you are not using the libsodium build system.

The list of included files in your SCons file looks way out of date and doesn't match the current libsodium source code.

Since you are not defining any macros automatically defined by the normal build system, you may also expect performance to be terrible.

**Comment by facekapow** [comment]
Updating to the latest stable libsodium solved the problem, thanks! (performance is actually great, btw)

**Comment by iefserge** [comment]
@jedisct1 thanks for the great library and looking into this. I'm curious what macros needs to be defined there to fix the performance?
