### ISSUE TITLE
Using modern datatypes (<stdint.h>)

### ISSUE THREAD

**Issue by duesee** [jedisct1/libsodium#413]
Just wanted to raise the question if it would make sense and be beneficial to move to the types provided by `stdint.h` e.g. `uint8_t`, `uint16_t`, `uint32_t`, `uint64_t`, etc. instead of using `unsigned char`, `unsigned int`, `long`, `unsigned long long int`, etc.

I find it always grueling working with the "original" types and it seems like `stdint.h` did a really good job here. Not sure about compatibility issues, etc.

**Comment by jedisct1** [comment]
C99 types are used everywhere internally, but at least libsodium 1.0 has to remain ABI-compatible with the original NaCl project.

The most annoying thing might be usage of `unsigned long long` instead of `size_t` for sizes.

This might change after a major update of the API involving other breaking changes. Probably for libsodium 2.x. But right now, the public API is not going to change.

Thanks for your input!
