### ISSUE TITLE
Directory structure not documented

### ISSUE THREAD

**Issue by Exaeta** [jedisct1/libsodium#430]
Could someone please provide documentation on the project and particularly the directory structure of libsodium? It's very hard for me to navigate this code.

**Comment by jedisct1** [comment]
The directory structure is essentially

`<high level operation name>`/`algorithm`/`implementation`

For example `crypto_stream/chacha20/vec` is contains the `vec` implementation of the `chacha20` algorithm, which is part of the `crypto_stream` high level API.

**Comment by Exaeta** [comment]
Ok, that explains part, but what about the header vs include structure?

Sorry if this seems tedious, I'm trying to plan a restructuring of libsodium to make a version that works within certain coding standards.

I have to move everything into a structure like:

```
include/generic/sodium/*.h
include/x86/sodium/*.h
include/sparc/sodium/*.h
src/generic/sodium/*.c
src/armv5/sodium/*.c
src/windows/sodium/*.c
```

So, I'd really appreciate if I could get a more detailed explanation of how the project chooses what implemenation to use on different architectures. Even if I can't get rid of the macros for now, I'd like to at least move all files into two directories (src, and include).

The reason all files are organized like this is to avoid the usage of macros when possible (via compiler `-Iinclude/generic -Iinclude/sparc`, etc.)

I also need to create concrete types (e.g. sha256::sum). For many primitives I have done this, but it can be difficult to figure out what the underlying primitive is when I just have e.g. "crypto_box" to work with (which I believe is either curve25519xsalsa20poly1305aes or curve25519xsalsa20poly1305xsalsa20)...

**Comment by jedisct1** [comment]
The whole point of the library is to expose a high-level API to perform operations without having to worry about what exact algorithms are being used underneath, and with what parameters.

But the algorithm for each high-level function is mentioned in the documentation.

The implementations are chosen at runtime, according to the CPU features. It all happens in `sodium_init()` that first retrieves the CPU features, then calls `_*_pick_best_implementation()` in order to select the presumably fastest implementation of each primitive for the detected CPU.

**Comment by Exaeta** [comment]
The problem is that I need exact algorithms. This code is designed to transmit data over the network, hence I need to be able to ensure that both ends are using the same algorithm. ;)
