### ISSUE TITLE
Question about "Poly1305"

### ISSUE THREAD

**Issue by Exaeta** [jedisct1/libsodium#443]
Is the "Poly1305" included in the library "Poly1305-AES" or "Poly1305-XSalsa20" or "Poly1305-ChaCha20" or something else? I know secretbox uses xsalsa20 for the message data, but there's no indicator about the type of encryption used by the MAC code.

**Comment by jedisct1** [comment]
Poly1305 computes a MAC. It doesn't perform any type of encryption.

AES, ChaCha20 and XSalsa20 are designed to encrypt data, but do not include any authentication tags.

If you need both authentication and encryption, and you usually do, you need to combine both. This is what `crypto_box*()` (XSalsa20+Poly1305), `crypto_aead_chacha20poly1305*()` (ChaCha20+Poly1305) and `crypto_aead_aes256gcm*()` (AES256+GCM. AES+Poly1305 would work, but nobody uses it) do.

You almost never need to call the `crypto_onetimeauth()` function directly, unless you are inventing your own constructions.

**Comment by Exaeta** [comment]
@jedisct1 
My understanding is that poly1305 creates a poly with a poly algorithm then encryts it with an encryption scheme. i.e. there is no such thing as just plain "poly1305" because that offers no security guarantee, it can be computed by anyone. The secret key provided to poly1305 is provided in the form of AES or xsalsa20 etc.
See e.g.: https://en.wikipedia.org/wiki/Poly1305
It seems the original algorithm was poly1305-AES, but I'm not sure which version got used in libsodium/crypto box...

**Comment by tarcieri** [comment]
@Exaeta 

Like @jedisct1 said, `crypto_box_*` and `crypto_secretbox_*` combine XSalsa20+Poly1305. The first 32-bytes(?) of the XSalsa20 keystream are used to derive a Poly1305 key. You can think of the result as "Poly1305-XSalsa20" if you'd like (although everyone else would just call it XSalsa20+Poly1305)

**Comment by Exaeta** [comment]
@jedisct1 
@tarcieri 
My understanding is that while NaCl and LibSodium both use Poly1305-Salsa20 as "Poly1305", Other variants of Poly1305 are used by other software, such as TLS, which uses Poly1305-ChaCha20.
This starts to get very confusing at that point. Since the encryption used by poly1305 is divorced from the encryption in the data stream...

**Comment by jedisct1** [comment]
"Poly1305-ChaCha20" means that two distinct functions are combined, in order to compute different things. The combination offers both encryption and authentication. Poly1305 can be used without any cipher, and ChaCha20 doesn't require Poly1305 either.

Poly1305 *is* guaranteed to be secure as long as the key is secret and never used with more than one message. One way to use it is to derive the key using a stream/block cipher. That key is not included in the output, and the nonce ensures its uniqueness.

Poly1305 is documented here: https://download.libsodium.org/doc/advanced/poly1305.html

This is not Poly1305-ChaCha20 nor Poly1305-Salsa20.
