### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [jedisct1/libsodium#446]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [x] Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [x] Upload the public key to a key server
* [ ] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [x] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [ ] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information:**
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by jedisct1** [comment]
Hi!

All tarballs have been signed since the very first release.

They are signed both with Minisign and GPG.

The public keys are available [in the documentation](https://download.libsodium.org/doc/installation/#integrity-checking), in the root folder of the download site, and on the MIT key server.

Signing every commit with GPG is not something I can easily do at the moment. Arch Linux should never use unstable, untested, possibly completely insecure code from the master branch of the git repository no matter what.

But releases will keep being signed!

**Comment by NicoHood** [comment]
Thanks for your reply. I might be wring, but i can only find the minisig on github.
https://github.com/jedisct1/libsodium/releases

Now I did not know about the alternative download page. Thanks for sharing this information.
