### ISSUE TITLE
web page https://libsodium.org/ is wrongly configured

### ISSUE THREAD

**Issue by tigusoft-vm** [jedisct1/libsodium#448]
"https://libsodium.org/" does not open in Firefox, it shows empty tab in firefox.

It seems the web server sends some wrong headers:

wget https://libsodium.org/
Last-modified header invalid -- time-stamp ignored.

**Comment by jedisct1** [comment]
Thanks for reporting this!

That page is served by Gitbook.com.

The `Last-Modified` property indeed returns an `UTC` timezone instead of `GMT`. I reported this using their contact form. Hope they address the issue soon!

Modern versions of Firefox seem to ignore the timezone and always assume GMT like other browsers, though.

**Comment by jedisct1** [comment]
```
last-modified: Sat, 14 Jan 2017 12:32:33 GMT
```

Apparently fixed!
