### ISSUE TITLE
Support Blake2 KDF?

### ISSUE THREAD

**Issue by jadamcrain** [jedisct1/libsodium#465]
New Blake2x spec out 12/03 defines a KDF:

https://blake2.net/blake2x.pdf

Would be nice if the existing blake2 api also exposed the KDF.

**Comment by jedisct1** [comment]
Hi!

Could you describe your immediate use case for it?

The main issue I have with BLAKE2X is an API issue.

It doesn't degrade to BLAKE2 for output sizes <= 512 bits. If it did, things would have been straightforward. Bump the max output size for `generichash()`, done. The API remains the same and everything remains simple.

But that is not the case. We have two similar functions, but different outputs.

So, where does BLAKE2X fit in the current API?

We can introduce a new high-level API, such as `crypto_xof`. So we can also put SHAKE in it.
Now, we have `shorthash`, `hash`, `generichash` and `same_as_generichash_but_output_sizes_can_be_longer_than_generichash`. That is awful.

BLAKE2X could be only available as a low-level function,  maybe within `generichash`. Unless there are common use cases that other constructions don't solve yet, that code will but around forever, but will rarely be used. Not great.

Or maybe the high-level API could use BLAKE2B for output sizes <= 512 bits, and transparently switch to BLAKE2X for larger output sizes. From a practical perspective, this is probably what makes more sense. But under the hood, it's ugly.

Actual use cases for it are probably the best indicators we can use in order to decide how BLAKE2X (and SHAKE) would fit in the current (or in a new) API. So, could you explain why you need it?

**Comment by jadamcrain** [comment]
Hi,

I have no immediate need. I'm currently extending a protocol specification that uses HKDF-HMAC-SHA256 for key derivation. I'd like to have support for BLAKE2 for lower latency on embedded systems,  but I could take the conservative route and use keyed BLAKE2 w/ HKDF or even the somewhat redundant HMAC construction of BLAKE2 for consistency.

I wouldn't want to create API difficulties for libsodium for something for which I have alternative choices. The only thing I've needed to write myself to implement this spec using libsodium as a backend was HKDF.

-Adam

**Comment by jedisct1** [comment]
BLAKE2 alone can be used for key derivation. See https://download.libsodium.org/doc/key_derivation/

And if you really need to derive many bytes from a single high-entropy key, `crypto_stream()` probably fits the bill. Under the hood, it is a hash function in counter mode.

**Comment by jadamcrain** [comment]
thank you.
