### ISSUE TITLE
Different values of "tag" in cifra and libsodium for the same function 

### ISSUE THREAD

**Issue by monicaphalswal** [jedisct1/libsodium#490]
I am using [`void cf_chacha20poly1305_encrypt(const uint8_t key[32], const uint8_t nonce[12], const uint8_t *header, size_t nheader, const uint8_t *plaintext, size_t nbytes, uint8_t *ciphertext, uint8_t tag[16])`](https://cifra.readthedocs.io/en/latest/chacha20poly1305.html#c.cf_chacha20poly1305_encrypt) from **cifra** and
 [`int crypto_aead_chacha20poly1305_ietf_encrypt_detached(unsigned char *c, unsigned char *mac, unsigned long long *maclen_p, const unsigned char *m, unsigned long long mlen, const unsigned char *ad,
 unsigned long long adlen, const unsigned char *nsec, const unsigned char *npub, const unsigned char *k); `](https://github.com/jedisct1/libsodium-doc/blob/master/secret-key_cryptography/ietf_chacha20-poly1305_construction.md) from **libsodium**. Both of them are suppossed to produce the same ciphertext which they are doing but the tag is coming out to be different. I am not able to understand why this is happening. Please help.

**Comment by jedisct1** [comment]
I had never heard about cifa before, but there are two "versions" of the ChaCha20Poly1305 AEAD construction.

The initial one, that was documented in early drafts, and the one in the final IETF document.

These versions don't compute the tag the same way. The IETF version adds some padding in order to provide better domain separation. The nonce sizes are also different: the IETF version extends the nonce but reduces the counter size.

libsodium provide both variants. You will find the similar functions with, and without the `_ietf` suffix. I don't know about cifra.

By the way, for embedded use, you may want to check out [https://github.com/jedisct1/libhydrogen](libhydrogen).
