### ISSUE TITLE
crypto_stream_xor_ic

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#498]
Is there a reason that there is no `crypto_stream_xor_ic` seeing that there's `crypto_stream_chacha20_xor_ic`, `crypto_stream_salsa20_xor_ic` and `crypto_stream_xsalsa_xor_ic` (which `crypto_stream_xor_ic` would alias)? I have a use-case for this which is why I'm asking

**Comment by jedisct1** [comment]
Hi Emil,

An `_ic` API requires the underlying cipher to be used in counter mode.

`crypto_stream()` is generic and cannot make any assumption about the underlying construction.

**Comment by emilbayes** [comment]
Do stream ciphers which don't use counters exist? Excuse my ignorance :)

**Comment by emilbayes** [comment]
Put another way; would it make sense to have a `crypto_stream_init`/`crypto_stream_update`/`crypto_stream_final` for generating a long stream from a stateful `crypto_stream`?

**Comment by jedisct1** [comment]
Sure, you can build a stream cipher out of a block cipher in any other mode, such as CBC. Even though counter mode has a lot of advantages, a justification for doing that could be reusing existing code in constrained environments.

Adding a state would be a better fit for the `randombytes_deterministic_*()` API, which is safer since users don't directly access the nonce and counter.

This will be added if at least another project needs it :)

**Comment by emilbayes** [comment]
Arr yes, that's kind of what I realised, but I wasn't exactly sure. Having a CSPRNG available, which can safely used as pad material in the same way that `crypto_stream` is used would be great. I'm working with @mafintosh to add encrypted communications to @datproject, and since the data is already authenticated and a nonce and key have been shared out of band, we just needed a way to encrypt a stream of bytes.
