### ISSUE TITLE
Expose a salsa20->stream_ic method

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#499]
Tangentially related to #498; would it be possible to expose a `_ic` method of [`salsa20->stream`](https://github.com/jedisct1/libsodium/blob/e5a196a8eef31d0f90437404e8e5f155f7c4c73e/src/libsodium/crypto_stream/salsa20/ref/salsa20_ref.c#L37-L39), where it is possible to pass a block counter instead of it just being zero? This would allow random-access to the PRNG, which would allow us to skip the whole `_xor` part for my use-case, which I mention in the previous issue

**Comment by jedisct1** [comment]
I'm a little bit reluctant to adding this. The API is really bloated already, especially since we have to always remain backward compatible.

So the rationale for adding new functions is that it shouldn't be possible to do the same thing using the currently available ones, or that it is required for interoperability, or that it is something frequently required.

`_xor_ic` is used internally and is required to build constructions where the first block is used to derive subkeys. 

Having direct access to the counter without xoring would be trivial to implement, but the need for it seems to be very rare.

So, if xor'ing a zeroed buffer is an option for your use case, I'd like to avoid adding such an API if possible.

**Comment by emilbayes** [comment]
Yes alright! Passing a zeroed buffer is actually what I do now, I was just curious as to why a `_ic` method wasn't exposed.
