### ISSUE TITLE
Feature Request: Blake2B as crypto_sign() hash function

### ISSUE THREAD

**Issue by athei** [jedisct1/libsodium#506]
Right now crypto_sign() uses sha512 as hash function. crypto_hash() uses blake2b which is mich faster. Could we have a crypto_sign() function that uses blake2b as its hash function?

**Comment by jedisct1** [comment]
I would also have liked to see BLAKE2b being picked over SHA512.

However, pre-hashed Ed25519 has been formalized by RFC8032, using SHA512 as the hash function. It is already required for Ed25519, so reusing it was a natural choice.

Using a different function means being incompatible with the standard and with other implementations, for no practical security benefits. 

Having both would be confusing and make the API more bloated for no reason.

Also, the prefix for the internal hash computations on prehashed messages is well defined for SHA512, not defined at all for other functions.

So we will have to invent ours, taking the risk of a collision with future revisions of the document.

If the difference in speed between both functions is really critical for your application, it's simple enough to prehash the message yourself before signing the resulting hash.

It's hard to maintain a balance between interoperability and going a little bit off-track to improve security or speed. In that case, the security improvement is not measurable and the speed difference is probably irrelevant to most applications.

So, let's stick to the standard, especially since it doesn't prevent anyone from using BLAKE2 instead if they really have to.
