### ISSUE TITLE
crypto_pwhash_str* hides some parameters

### ISSUE THREAD

**Issue by sonOfRa** [jedisct1/libsodium#509]
Hello,

is there a reason the [crypto_pwhash_str*](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_pwhash/crypto_pwhash.c#L135)  functions hide the configurability of the output length and salt length? I'm in the process of adding argon2 password hashing to OpenLDAP, and was asked to provide backends for both the libsodium and argon2 implementations - in the reference implementation, the "formatted" functions provide all the parameters (salt length, output length, memory cost, cpu cost, parallelism). Libsodium forces parallelism to 1 in all cases (which I find reasonable), but it also forces the salt length to 16 and output length to 32 in the str* versions of the functions.

Is this a design decision, or would you be willing to accept code that exposes these parameters in the those functions?

Best regards,
Simon

**Comment by jedisct1** [comment]
Hi,

This is a design decision.

Like most high-level APIs provided by Sodium, reasonable defaults have been chosen in order to keep the functions simple to use, and to prevent users from choosing insecure or overkill parameters.

A large salt would have no benefits; the Argon2 paper explicitly mentions that a 128 bit salt is enough for all applications.

256 bits is the key size used by most other constructions in the library. A longer output wouldn't be necessarily useful, and if a shorter one is needed, the output can be safely truncated.

**Comment by sonOfRa** [comment]
Thank you for the quick reply!

I'll pass this on and use the libsodium default parameters also in the argon2-backed version.

**Comment by jedisct1** [comment]
Thank you for adding Argon2 to OpenLDAP!
