### ISSUE TITLE
BLAKE2s (Conditional Feature Request)

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium#531]
I'm working on a spec for a project that uses [Noise](https://noiseprotocol.org/). The example protocols they give are:

* Noise_XX_25519_AESGCM_SHA256
* Noise_N_25519_ChaChaPoly_BLAKE2s
* Noise_XXfallback_448_AESGCM_SHA512
* Noise_IK_448_ChaChaPoly_BLAKE2b

Currently, most protocol permutations are possible, except anything requiring Curve448 (#254) and BLAKE2s.

Therefore, I'd like to propose the following: **If (and only if) Curve448 support is added**, can we have BLAKE2s as well? This would allow libsodium users to implement every possible Noise implementation that conforms to the spec. (If Curve448 support is never added, then adding BLAKE2s alone would not satisfy this outcome, so it's not worthwhile to pursue in and of itself.)

Otherwise, users will need to hook into a second crypto library (besides libsodium) that offers these protocols if we want this interoperability.

**Comment by jedisct1** [comment]
I'm very reluctant to this, or more generally to adding anything that provides no value over what is already available.

If two functions doing exactly the same thing are available, this only adds confusion. The current API is already way too bloated.

BLAKE2S(X) is used by Hydrogen because it mainly targets 16-bit and 32-bit platforms, but libsodium targets devices that are mostly all 64-bit nowadays.

**Comment by paragonie-scott** [comment]
> I'm very reluctant to this, or more generally to adding anything that provides no value over what is already available.

I understand. I'm also aware that Curve448 support is unlikely to be added, hence why I made the request contingent upon the unlikely feature request.

(For what it's worth, I'm already specifying `*_25519_ChaChaPoly_BLAKE2b` in my project as the only supported option.)

**Comment by jedisct1** [comment]
Sorry Scott :(
