### ISSUE TITLE
use getrandom() with glibc if available

### ISSUE THREAD

**Issue by hannob** [jedisct1/libsodium#535]
the randombytes_sysrandom() currently contains this code:

```
#  ifdef __dietlibc__
        readnb = getrandom(buf, size, 0);
#  else
        readnb = syscall(SYS_getrandom, buf, (int) size, 0);
#  endif
```

Which means getrandom is only used for dietlibc. Latest versions of glibc contain getrandom as well, so the syscall workaround shouldn't be needed any more. Should this be changed to use getrandom if it's available? (There's probably some #ifdef-ing that can check for the glibc version.)

**Comment by jedisct1** [comment]
I'm not convinced that there is any benefits in calling the glibc function rather than the syscall directly.

Using the syscall works on a wider range of systems without requiring additional checks, and may prevent endless support issues with people using unusual combinations of glibc/glibc headers/kernels.
