### ISSUE TITLE
Proposal: libsodium 2.0: XChaCha20 as default cipher for *box

### ISSUE THREAD

**Issue by tarcieri** [jedisct1/libsodium#554]
There are presently 5 ciphers of "Snuffle 2005" heritage supported by libsodium:

- Salsa20
- XSalsa20
- ChaCha20 (djb version)
- ChaCha20 IETF
- XChaCha20 (using ChaCha20 IETF w\ extended nonce)

The IETF edition of ChaCha20 is used by TLS and is the most widely supported of these three ciphers, being present in the crypto libraries for most TLS implementations.

Salsa20 is pretty much only supported by libraries of NaCl heritage, yet it remains the default option for *box constructions.

I think all of the *box constructions should switch to using XChaCha20 by default. This would be a breaking change, hence "libsodium 2.0".

---

Perhaps a separate, but still somewhat related issue: I would like to see the non-IETF version of ChaCha20 deemphasized. Presently the functions for ChaCha20 look like:

* `crypto_aead_chacha20poly1305_*`
* `crypto_aead_chacha20poly1305_ietf_*`

To someone not intimately familiar with the ChaCha20 backstory here, this reads like "the normal ChaCha20 I should use" versus "weird IETF version of ChaCha20", when really the opposite is true: everything new using ChaCha20 should probably use the IETF version.

At the very least I would suggest the other version have something added to its name to suggest it shouldn't be used. Perhaps rename it to `crypto_aead_chacha20poly1305_legacy_*` to emphasize it is probably not the best choice.

**Comment by jedisct1** [comment]
I agree that there are way too many Snuffle2005 variants, and more generally way too many constructions.

There's still a major downside to XChaCha20: it's supported by virtually nothing except libsodium. But of all variants, it's by far the most versatile one, and the one I would recommend for all use cases.

Besides Salsa20, libsodium 2 would be a good opportunity to get rid of other legacy requirements that we currently have to stick with in order to remain compatible with NaCl. If only the usage of `long long` everywhere for sizes is a nonsense.

The [libhydrogen API](https://github.com/jedisct1/libhydrogen/wiki) is essentially what I envision the libsodium 2 API to be. Stronger types for keys might be added.

It's a bit early to pick what the `*_box` API should be. NMR might be a good property to have. I still have some hope that the CAESAR competition will eventually select a winner.

Introducing version 2 right now with just xsalsa replaced with xchacha would not help anyone. It would just break backward compatibility without bringing any benefits. Salsa is not broken.
Ditto for renaming a function at this point. It would just break existing applications. ChaCha20/djb is not broken. And it's also present in other libraries. Sure, it's not the best choice. XChaCha20 is.

The documentation on [AEAD constructions](https://download.libsodium.org/doc/secret-key_cryptography/aead.html) tries to describe this. Rather than break the current API (which is exposed differently in other languages), I'd rather improve the documentation.

**Comment by tarcieri** [comment]
> There's still a major downside to XChaCha20: it's supported by virtually nothing except libsodium. 

The same could be said of Salsa20.

> Introducing version 2 right now with just xsalsa replaced with xchacha would not help anyone. It would just break backward compatibility without bringing any benefits

libsodium has helped create an ecosystem of Salsa20 users. As an early advocate and user of libsodium, I thought this was a good idea a the time, but it has turned out to be a derelict cipher which has contributed to a non-interoperable cryptographic ecosystem.

**Comment by jedisct1** [comment]
There are quite a few popular implementations of the salsa20-based `box` constructions around. The one in the golang stdlib, and all the ones based on tweetnacl come to mind.

Switching to xchacha20 wouldn't improve interoperability. The `box` API remains very specific to NaCl derivatives anyway.

If interoperability with other libraries implementing chacha20 is a concern, sodium already has compatible AEAD implementations. If you really want the `box` API with xchacha20, it's already there as well (`crypto_box_curve25519xchacha20poly1305`).

Unless many other libraries implement a `box` API (which is unlikely, if only because as an API, it isn't that great) based on xchacha20, there are no reasons to make a breaking change to the current high-level `crypto_box` API.

**Comment by anergiz** [comment]
Hi I am a developer in the [tink](https://github.com/google/tink) project.
Currently I am implementing snuffle variants in the project and I have a question regarding to this topic. I see that libsodium supports two versions of XChaCha20, one is similar to the XSalsa20 in the nacl box implementation (secret_box or crypto_box version) and the other one is using the IETF version (which seems to be a standalone aead construct). Is there a particular reason IETF version is implemented for XChaCha20? Please see this line:
https://github.com/jedisct1/libsodium/blob/8b9b6a54be5490449e0c5e535aa257d6406b04b2/src/libsodium/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c#L33
is prepadding the remaining 64bit nonce to fit the IETF version 96bit nonce slot which seems to be a little bit unusual. With X variants based on IETF, we might expect a 224bit nonce (128+96) however this seems to be an overkill so why take space from the counter at all? Also with the aead construct to be different between two versions (i.e., IETF skips the last 32byte keystream with counter 0), we get something different than the structure XSalsa20Poly1305 follows.
Thanks!

**Comment by tarcieri** [comment]
> I see that libsodium supports two versions of XChaCha20, one is similar to the XSalsa20 in the nacl box implementation (secret_box or crypto_box version) and the other one is using the IETF version (which seems to be a standalone aead construct). 

Can you point to the specific lines of code you're referring to? There is only one primitive actually exposed, and it is the combination of the two things you just mentioned: it's using the same technique as XSalsa20, but with the IETF version of ChaCha20

**Comment by zx2c4** [comment]
The IETF version is implemented for XChaCha for two reasons:

1. Consistency.
2. Because the construction hashes in lengths and padding into the authenticator, which some people might prefer to the non-IETF construction.

However, their interface is essentially the same, with each using a 24-byte nonce. The [XSalsa](https://cr.yp.to/snuffle/xsalsa-20081128.pdf) analysis is for a 192-bit nonce, so that's what we're using.

I haven't checked to see how this plays out in the particular code in libsodium, but the construction here in theory has the added benefit of allowing encryptions of length 2^64, rather than 2^32.

**Comment by anergiz** [comment]
@tarcieri see here: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c
This one implements XChaCha20Poly1305 similar to XSalsa20Poly1305
which the crypto_box interface is using.
The aead construct I have linked previously is implementing XChaCha20Poly1305 with IETF Poly1305 construction.

@zx2c4 I have looked at the code a little bit closer and see that although the aead construct seems to be using the IETF construction, for ChaCha20 it doesn't (it only uses the parts of IETF for the Poly1305). However I still believe this is very confusing. Using one version of Poly1305 for aead and the other for the crypto_box. How is this consistent?
Another thing that I noticed, please see this line:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_aead/xchacha20poly1305/sodium/aead_xchacha20poly1305.c#L33
it is filling the lower end of the nonce, meaning the int in 13th index in the block will be zero just like the original ChaCha20 first block construction. So it is actually the same as original ChaCha20. And see:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_stream/chacha20/ref/chacha20_ref.c#L187
It is still incrementing the 13th int even if the call comes from the ietf version. So if someone encrypts a message > 256GB (unlikely but still), libsodium increments the nonce. Though I got to admit it doesn't fail even for the failure case. It would generate different ciphertext than the rfc doc after 256GB mark.

**Comment by zx2c4** [comment]
> I have looked at the code a little bit closer and see that although the aead construct seems to be using the IETF construction, for ChaCha20 it doesn't (it only uses the parts of IETF for the Poly1305). 

I'm unable to parse this sentence or see what it corresponds to. XChaCha20Poly1305 in libsodium is just the IETF ChaCha20Poly1305, except being passed a key derived from HChaCha20, and only using 64-bits of the nonce field.

Composing one from another like this seems to be a consistent way of designing things.

Could you clarify in a way that I can parse?

> It is still incrementing the 13th int 

Yes, this is why I mentioned that xchacha20poly1305 being constructed this way -- using the 192-bit nonce -- allows us to still have 2^64-byte message sizes. Seems like a good thing to me.

**Comment by anergiz** [comment]
What we are saying is the same thing actually. XChaCha20Poly1305 is similar to XSalsa20Poly1305 in nacl but it is using the Poly1305 defined in the RFC. ChaCha20 stays the same after the key derivation with HChaCha20. I was confusing myself when I see the method name includes ietf and thinking that ChaCha20 will have 4 bytes counter and nonce will be 224bit instead.
If in the future XSalsa20Poly1305 is implemented under the aead, would that be using the RFC Poly1305 as well?

For consistency argument, there are two different version of XChaCha20Poly1305, the one you are talking about and the one, [crypto_secretbox_xchacha20poly1305_detached](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c#L18), that is used under the hood of [crypto_box_curve25519xchacha20poly1305_open_easy](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_box/curve25519xchacha20poly1305/box_curve25519xchacha20poly1305.c#L151).
How is this consistent (in the sense of composing one from another)?

**Comment by zx2c4** [comment]
> For consistency argument, there are two different version of XChaCha20Poly1305, the one you are talking about and the one, crypto_secretbox_xchacha20poly1305_detached, that is used under the hood of crypto_box_curve25519xchacha20poly1305_open_easy.
> How is this consistent (in the sense of composing one from another)?

Oh, ugh, that's disgusting. I wonder how that happened. I remember Frank initially implemented XChaCha20Poly1305 in this open coded way, and then I ripped it out and built it fresh from the existing AEAD. I wonder if when I did that I just didn't see the crypto_box implementation? Or if that came later and Frank just forgot?

@jedisct1 could you shed some light on this? If it's possible, I think I'd prefer to change crypto_box to use the aead implementation, instead of open coding all of that. I can submit a patch for this, with your blessing.

**Comment by jedisct1** [comment]
crypto_box is crypto_box, aka crypto_box_xsalsa20poly1305 (removed the curve25519 prefix which is not relevant here).

It's a NaCl-specific construction, that doesn't accept any additional data, and that doesn't relate to any RFC. Nobody's implementing crypto_box except NaCl and derivatives.

It's using salsa20, and this is not going to change.

crypto_box_xchacha20poly1305 is exactly crypto_box_salsa20poly1305 with xchacha20 instead of salsa20. This remains consistent with the original NaCl construction. This function is undocumented, and was just there to be consistent with xchacha being added to other APIs.

Something using the IETF variant must be called crypto_box_xchacha20_ietfpoly1305. It can be added, but I'm not sure that it's useful. OpenSSL is not going to implement crypto_box anytime soon and existing crypto_box implementations all implement only salsa20.

**Comment by zx2c4** [comment]
Oh, okay, that makes sense.
