### ISSUE TITLE
libsodium crosscompile win32 docker

### ISSUE THREAD

**Issue by wirwolf** [jedisct1/libsodium#570]
Hello. I can not compile libsodium in docker container for win32.
Dockerfile: https://pastebin.com/gfW0trg2
output errors:https://pastebin.com/TFXJLe3N

**Comment by jedisct1** [comment]
You're trying to run tests. Windows excutable files will not run on a different operating system without emulation.

**Comment by wirwolf** [comment]
1. How to disable tests?
2. Can you fix bash file in dist-build?

**Comment by jedisct1** [comment]
Don't run "make check" if you want to build something and not check that it actually works.

That's a really bad idea, though, especially since it can have serious security implications.

Do you really *need* to cross-compile it?

Official pre-compiled binaries compiled and tested on native systems are available for download; I would recommend using these. Or at least, compile on a real Windows system. Or use Wine to run the tests, but this is a last resort.

**Comment by wirwolf** [comment]
I use sodium lib in my blockchain project and I download and compile library because we use static compilation.

**Comment by jedisct1** [comment]
The precompiled binaries (both the ones for MingW and the ones for Visual Studio) include static libraries.

I wouldn't recommend releasing a blockchain project relying on a crypto library that was never tested on the platform it's supposed to run on.
