### ISSUE TITLE
cross-compile mac os x86_64

### ISSUE THREAD

**Issue by wirwolf** [jedisct1/libsodium#580]
Hello. I can't cross-compile library for mac os.
make file: https://github.com/minexcoin/minexcoin/blob/builder/depends/packages/libsodium.mk
error: 
ld: file was built for unsupported file format ( 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): ..../depends/x86_64-apple-darwin11/lib/libsodium.dylib for architecture x86_64

Please help!.

**Comment by wirwolf** [comment]
When i compile library in mac machine everything is fine

**Comment by jedisct1** [comment]
What compiler are you using? What environment? Can you build a hello world app that runs on macOS with it?

**Comment by jedisct1** [comment]
In any case, I would highly recommend avoiding cross-compilation if possible.

You would be using something that has never been tested, obviously unsupported, for which you didn't even run the test suite to check that it works. For a payment system.

Build on the host you are going to run the application on. Especially since you have a Mac, and you want to build for Mac.
