### ISSUE TITLE
Problem compiling on Mac with CLMUL

### ISSUE THREAD

**Issue by jhellenthal** [jedisct1/libsodium#585]
According to the author of rbnacl-libsodium there is a problem on mac with CLMUL on this CPU
https://github.com/cryptosphere/rbnacl-libsodium/issues/15

Anything else I can provide or aide to resolve this problem ?
[gem_make.txt](https://github.com/jedisct1/libsodium/files/1252594/gem_make.txt)

**Comment by jhellenthal** [comment]
Also should note that I am using MacPorts for this installation with ruby 2.4.1 bundled with metasploit. And fails to compile.

**Comment by jhellenthal** [comment]
Seems this is related https://github.com/jedisct1/libsodium/issues/234

**Comment by jedisct1** [comment]
Hi,

Your compiler toolchain appears to be broken.

There is an obsolete binutils version (probably installed by Macports) that comes before Xcode in your PATH.

So, clang emits code designed to be compiled by the version of `as` also bundled with Xcode.

But instead, the `as` command from a binutils version you installed gets picked, and that one is very old compared to what clang expects.

Remove these binutils tools, or adjust your PATH so that things used by Macports do not replace the tools already provided by Xcode.
