### ISSUE TITLE
Which parameter for parallelism does libsodium chooses for Argon2?

### ISSUE THREAD

**Issue by athei** [jedisct1/libsodium#590]
I noticed that I can't configure the parallelism parameter for Argon2? How is it set in libsodium?

**Comment by jedisct1** [comment]
Hi!

It doesn't support parallelism, and I'm not really convinced that this is necessary, or even a good thing since it makes resource exhaustion attacks easier. If a password hashed using a single core can be found in a 2 days, having used four cores instead wouldn't have increased that time/cost by much.

In order to actually make the function useful, you want to increase that time by 10000x by raising the ops and memory costs, not just use a few additional CPU cores.

That being said, libsodium can *verify* Argon2 hashes with parallelism > 1.

**Comment by athei** [comment]
I don't use it for password storage but for key derivation. Therefore I need to tell some implementers which parameters they have to use for argon2 to derive the same key that is then used for a symmetric cipher. Do I tell them to set parallelism = 1?

**Comment by jedisct1** [comment]
Correct. You can just tell them to set the parallelism to 1.

**Comment by YellowOnion** [comment]
@jedisct1 I'm a little confused over your justifications here with excluding the parallelism parameter.

I assume the reason you can increase the parallelism is for low powered devices like mobile phones, by specifying a low number like 4-8 you increase verify speed, and lower power usage on a mobile device, without sacrificing too much in the way of GPU cracking.

I'm currently looking into way get verification down on KeePass2Android, because it's about 50x slower than the Desktop app, and my first thought was to increase memory usage & parallelism, since GPUs tend to run out of memory before they become saturated.

**Comment by mimoo** [comment]
> since it makes resource exhaustion attacks easier

AFAIK there exist no insecure parameters for Argon2, so I don't think allowing parallelism would become an issue.
