### ISSUE TITLE
Am I in the Right Place?

### ISSUE THREAD

**Issue by benjaminBrownlee** [jedisct1/libsodium#598]
I am a learning web developer looking for secure way to store passwords on a MySQL database.  Intuitively,  I thought hashing and salting were the strongest ways to put these passwords away beyond anyone's reach (in fact, the server itself has no key to reverse it), and Libsodium has one of the biggest reputations in this area.  I am using a virtual Linux environment -- Cloud 9 if you are familiar with it --  and I want something that can run on the Apache PHP server for reasons described above.  I have glanced through the documentation, but is rather dense, and I can't figure out if I have found what I was looking for. I would personally prefer a stand-alone PHP file with the methods I need to hash and verify passwords, but this library looks utterly complicated.

**Comment by jedisct1** [comment]
Hi Benjamin,

No need for libsodium.

In order to securely store hashes that will let you verify passwords, PHP offers a password hashing API:

http://php.net/manual/en/ref.password.php

And that one will get even better with PHP 7.2.0 that will be released in a couple days.

Great read on that topic: https://paragonie.com/blog/2016/02/how-safely-store-password-in-2016
