### ISSUE TITLE
Hierarchical Deterministic Keys

### ISSUE THREAD

**Issue by mdyring** [jedisct1/libsodium#609]
First of all, thanks for the excellent work on this library!

I believe a useful addition to the library would be HD keys, possibly based on the "BIP32-Ed25519 Hierarchical Deterministic Keys over a Non-linear Keyspace" paper available here:

https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/master/topics-and-advance-readings/HDKeys-Ed25519.pdf

**Comment by jedisct1** [comment]
Probably not, unless there's a common need for this besides cryptocurrencies.

**Comment by mdyring** [comment]
I do believe this will be useful not just cryptocurrencies, but apply more broadly.

For instance most blockchain applications (not just of a financial nature) would benefit from the ability to derive keys to preserve anonymity when signing.

**Comment by jedisct1** [comment]
That still remains a very specific use case; I'm not sure it's worth adding to a generic library.

**Comment by mdyring** [comment]
Well I thought it was worth a try. :-)

I'll see if the Evernym guys (authors of the paper) have released it under a OS license.

Best regards,
Martin

**Comment by tarcieri** [comment]
@mdyring there are a number of problems with attempting to specify a scheme like this on an elliptic curve with cofactors, and specifically the "clamping" operations:

https://moderncrypto.org/mail-archive/curves/2017/000858.html

I asked on the CFRG list about pursuing a standard for this sort of thing before coming to realize that specifying such a thing in terms of Ed25519 is probably a bad idea for the reasons discussed on the above thread.

All of these concerns go away if you have a prime order group. There is work underway to specify a means of encoding non-malleable prime order groups which otherwise use Ed25519 curve arithmetic called "Ristretto", based on Decaf:

https://eprint.iacr.org/2015/673.pdf

This uses a different wire format than Ed25519, but would eliminate all of the complexity presently involved in generating child scalars.

If you are interested in this sort of thing, I would recommend waiting for an official "release" of Ristretto and a Ristrestto-based EdDSA.
