### ISSUE TITLE
Forced update deleted an old stable commit

### ISSUE THREAD

**Issue by chris-doclily** [jedisct1/libsodium#611]
My remotely hosted CI system has been down since October 1st, and I've just learned from the host that the cause is that libsodium, a submodule in my repository, cannot be cloned. It cannot be cloned because the commit that my repository has set for libsodium no longer exists, as shown in this snippet of the output of "git submodule update --init --recursive":
```
error: Server does not allow request for unadvertised object 8d021b3f4980b924e0eb9cd0d491981b875c71f6
Fetched in submodule path 'deps/libsodium', but it did not contain 8d021b3f4980b924e0eb9cd0d491981b875c71f6. Direct fetching of that commit failed.
```
I just now ran "git fetch" within my local copy of the submodule, and it showed that there was a forced update in the "stable" branch.
```
$ git fetch
remote: Counting objects: 2969, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 2969 (delta 1056), reused 1079 (delta 1047), pack-reused 1878
Receiving objects: 100% (2969/2969), 723.47 KiB | 700.00 KiB/s, done.
Resolving deltas: 100% (1926/1926), completed with 227 local objects.
From https://github.com/jedisct1/libsodium
 + 8d021b3f...b6bad221 stable        -> origin/stable  (forced update)
 + c59825e0...214552f8 coverity_scan -> origin/coverity_scan  (forced update)
   00212b26..90f5b55a  master        -> origin/master
 * [new tag]           1.0.2         -> 1.0.2
 * [new tag]           1.0.13        -> 1.0.13
 * [new tag]           1.0.14        -> 1.0.14
 * [new tag]           1.0.15        -> 1.0.15
```
I assume that the forced update is what deleted the commit I was referencing.

This disruption has cost my company a lot of time, and I'd like to avoid disruptions such as this one in the future. Is there something that I should be doing differently? Was I wrong to point the submodule at this commit, which was the tip of the "stable" branch in an older version of libsodium?
```
commit 8d021b3f4980b924e0eb9cd0d491981b875c71f6
Author: Frank Denis <github@pureftpd.org>
Date:   Tue May 16 12:40:36 2017 +0200

    Move CRYPTO_ALIGN after the `struct` keyword
    
    Fixes #543
```

**Comment by jedisct1** [comment]
The `stable` branch is the latest release, plus additional minor bug fixes.

When a new release is tagged, the stable branch is usually rebased onto the new version. Since both branches diverge after a release, merging all the changes from a new release back to a the stable branch can be quite tricky.

But more importantly, having the stable release always rebased on the latest release makes it easier to see what exact changes have been done in the stable branch compared to that release. Some ports systems and linux distributions include additional patches to fix last-minute bugs or portability issues. Having individual , clearly identifiable patches in the stable branch, can be very useful in that context.

If you want to use a specific revision instead of a release tag or follow the stable branch, you can clone the repository, and check it from there.

But a way more common practice for CI and deployment when specific versions are needed is to build packages. Build a package for your distribution from the exact version you need, possibly with your own changes, and use that package in your CI system.

**Comment by lakeman** [comment]
Your current method of rebasing the stable branch is throwing away history, making it impossible to see what post-release fixes had been applied to older releases. This doesn't strike me as being very "stable" at all.

I think you should at least tag the old stable branch before you push a new rebased stable branch. Though I think that introducing a merge commit, even if there are no actual changes merged, would provide a more descriptive history.
