### ISSUE TITLE
Considering clean the round key buffer of AESNI encryption/decryption

### ISSUE THREAD

**Issue by romangol** [jedisct1/libsodium#617]
I noticed that in libsodium/src/libsodium/crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c the round key buffer of AES (i.e., const __m128i *rkeys) is not cleaned after then encryption or decryption, which leaves the sensitive information on the stack. In some other crypto libraries such as Botan, this information is immediately cleaned after the encryption/decryption (The AES cipher is implemented as a class and the destructive function is responsible for cleaning the round key buffer as a data member of the class).

**Comment by jedisct1** [comment]
Unfortunately, this is tricky to do reliably, if possible at all.

States, that can be stored on the heap, can be, and generally are cleaned after finalization.

But local variables are another story. See [zeroing buffers is insufficient](http://www.daemonology.net/blog/2014-09-06-zeroing-buffers-is-insufficient.html) for some background on this.

Tagging the round keys with `volatile` would force a `load` every time they are accessed. The performance hit would be significant, and at the end of the day, we may leak more keys as it may prevent some of these to be only stored in registers.

In many applications, it's also very likely that the key itself is on the stack around the time these functions are called.

Maybe what we can do is add a `sodium_stack_burn()` function that can be called to wipe the stack after we're done working with a key. The same function can attempt to wipe xmm registers as well (attempt, because even if we use assembly to do so, the compiler can save them and restore them afterwards).

The real solution for this would be having some support from the compiler. [This proposal](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69976) for gcc looked promising.
