### ISSUE TITLE
implement BLAKE2x?

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#623]
@jedisct1: according to https://blake2.net/, the BLAKE2x hash function is not yet finalized, but is it possible to implement support for the current draft proposal (https://blake2.net/blake2x.pdf) in libsodium? Maybe call it `crypto_hash_blake2x_experimental()` or something like that and make it clear that the implementation is not final and could still change? (Though apparently the community is comfortable with using it already, i.e. Adam Langley has merged BLAKE2x into Go).

I am probably going to try implementing it myself, and if there is interest I could do it as a libsodium pull request.

**Comment by jedisct1** [comment]
A short implementation of BLAKE2X was present in the first version of [libhydrogen](https://github.com/jedisct1/libhydrogen/): https://github.com/jedisct1/libhydrogen/blob/v0/impl/hash.h
You can reuse that if you wish.
The current version doesn't have it any more since the sponge construction already allows an arbitrary output size.

The main issue I have with merging it to Sodium is that fact that nobody ever asked for a XOF ever. Probably because a short hash to derive a key, followed by `randombytes_deterministic()` achieves pretty much the same thing.

So, if it gets merged but nobody uses it, even more if marked as experimental, this will end up being code bloat, abandoned and barely tested.

**Comment by ivmaykov** [comment]
tell me more about this sponge construction :) Specifically, does a function which "computes a short hash to derive a key, followed by `randombytes_deterministic()`" act like a random oracle?

**Comment by jedisct1** [comment]
If the hash function is keyed (regular BLAKE2 can be used for that purpose), it does.

**Comment by ivmaykov** [comment]
Does the function not act like a random oracle if we use BLAKE2b without a key to seed the PRNG? Context: we are trying to build an efficient XOF.

**Comment by jedisct1** [comment]
If you don't use a key, the PRNG will be exactly the same for a given hashed message, no matter what the application is. This removes the "random" property expected from something that has to act as a random oracle. 

The argument for using a XOF vs a hash + a DRBG  is that the later might be vulnerable to internal collisions: two messages producing the same key, so the same stream.

This is very unlikely to ever happen with a 256-bit subkey. If a collision happens, it really means that the core hash function is completely broken. And in this case, it would imply that BLAKE2X is completely broken as well.

**Comment by jedisct1** [comment]
So, to answer your original question, and although BLAKE2X is in the roadmap, I don't think it will be added in a near future.

It's efficient, and the changes compared to BLAKE2 are minimal, but since it seems to be a niche use case, I'd rather put it on the back burner until it becomes something applications frequently need.

**Comment by jedisct1** [comment]
And you got me really curious about what you are currently building :)

**Comment by ivmaykov** [comment]
@jedisct1 it's a pretty interesting problem, but I can't really tell you too much about it unless you come work for us :)

vague answer: we need to verify the authenticity of a map<string, string> that is distributed to many machines and can be updated with deltas. We're thinking of using LtHash over the entire map + signature over the LtHash value to provide the authenticity guarantee. We are using an XOF to generate the hash value for each map element.

**Comment by ivmaykov** [comment]
By the way, I ended up implementing Blake2xb using libsodium's blake2b implementation as the underlying engine, was pretty easy.
