### ISSUE TITLE
[libsodium.js - webassembly] Error when changing totalMemory

### ISSUE THREAD

**Issue by openidauthority** [jedisct1/libsodium#631]
A recent change (https://github.com/jedisct1/libsodium/pull/608) allows changing the totalMemory for password hashing.

However, if I add *64kb of memory or more* (beyond the 16Mb default), I get an error in the console:
```
Uncaught (in promise) abort({}) at Error
    at h (sodium.js:1:4282)
    at y (sodium.js:1:4433)
    at X (sodium.js:1:7708)
    at sodium.js:1:17749
    at <anonymous>
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

Here is my test script:
```
<script>
    window.sodium = {
        totalMemory: 16777216 + 65536
    };
</script>
<script src="sodium.js"></script>
```

I am able to use the additional memory, but would like to avoid the error in the console.

**Comment by jedisct1** [comment]
This seems to be the raised error:

```
failed to asynchronously prepare wasm: LinkError: imported Memory with incompatible size
```

Any idea, @buu700 ?

**Comment by buu700** [comment]
Hmm, that's interesting. It looks like changing `TOTAL_MEMORY` from 16777216 breaks the standard build and changing it from 83886080 breaks sumo. My first guess was that it had something to do with the ratio between `TOTAL_MEMORY` and `TOTAL_STACK`, but `TOTAL_STACK` is the same in both builds.

I have no idea, but it seems like emscripten must be changing more than just the value of a variable in its output based on the build-time value of `TOTAL_MEMORY`. It may be helpful to diff unminified versions of both builds.

**Comment by jedisct1** [comment]
Emscripten doesn't seem to change anything else:

```js
 var TOTAL_STACK = Module['TOTAL_STACK'] || 5242880;
-var TOTAL_MEMORY = Module['TOTAL_MEMORY'] || 16842752;
+var TOTAL_MEMORY = Module['TOTAL_MEMORY'] || 16777216;
 if (TOTAL_MEMORY < TOTAL_STACK) Module.printErr('TOTAL_MEMORY should be larger than TOTAL_STACK, was ' + TOTAL_MEMORY + '! (TOTAL_STACK=' + TOTAL_STACK + ')');

 // Initialize the runtime's memory
```

**Comment by buu700** [comment]
Huh, well in that case, can this issue be reproduced with the unminified code?

**Comment by jedisct1** [comment]
What actually changes in the Wasm code.

**Comment by buu700** [comment]
Ah, that makes sense. Maybe there are some optimizations applied based on the memory size? Out of curiosity, does the asm.js change too, or only the wasm base64?

If changing the memory size at run time like this isn't an option, maybe it'd be worth providing additional builds of both sumo and standard with different memory sizes that correspond to the different password hashing options and/or an alternate build with dynamic memory growth enabled.

**Comment by jedisct1** [comment]
The asmjs code doesn't change besides the `TOTAL_MEMORY` definition.

The wasm code could be patched (it's the same except 4 bytes), but that would be pretty ugly.

**Comment by buu700** [comment]
Ah, got it. Yeah, patching that would be ugly, but it sounds like it's at least fixable in emscripten without too much hassle or any loss of performance optimization. I'll open an issue there.

**Comment by buu700** [comment]
Based on Derek's comment in that emscripten issue thread, apparently `ALLOW_MEMORY_GROWTH` isn't as big a deal for wasm performance as it is for asm.js performance. I couldn't find any discussions or benchmarks specifically backing that up, but based on the amount of effort that I see has gone into that feature since 2015 (https://github.com/WebAssembly/design/issues?utf8=%E2%9C%93&q=memory+growth), it sounds credible.

That being the case, as long as performance isn't obviously drastically worse in testing, maybe the best path forward for libsodium.js is to enable memory growth, decrease the sumo build's total memory to parity with the standard build's, and kill this feature for overriding the total memory through `window.sodium`.

The fallback asm.js performance would be worse (which we already basically don't care about since we're already stripping the `'use asm'` and `-Oz`ing and uglifying it), but in theory the wasm performance would be minimally impacted and in return users could freely run `crypto_pwhash` with whatever mem limits they want without a lot of hassle or premature RAM consumption. Performance aside, would we have any reason to believe that this could introduce a new side channel attack vector?

**Comment by jedisct1** [comment]
That would be ideal, and I don't see any serious implications here.

Still, this requires quite a bit of benchmarking on all JS engines.

**Comment by buu700** [comment]
Awesome, sounds good. Just saw the benchmarks you're posting on Twitter; is the plan to test wasm with `ALLOW_MEMORY_GROWTH` as part of that?

**Comment by jedisct1** [comment]
Yes. This is why the benchmark scripts were originally made for :)

**Comment by buu700** [comment]
Nice, hopefully we'll get some good news then!

**Comment by jedisct1** [comment]
I got bad news. The overhead is massive.

`ALLOW_MEMORY_GROWTH` makes Argon2 twice as slow. Many other tests got 3x or 4x slower.

:(

**Comment by buu700** [comment]
Ah, well that sucks :/. I'll go back and reopen the emscripten issue.

**Comment by buu700** [comment]
By the way, do you know if the Argon2 slowdown persisted after the first run?

Don't want to derail the other thread since it seems like a way to change the wasm total memory is still needed,, but at least it might _also_ be worth allowing memory growth if the result is a one-off slowdown rather than an error.

**Comment by jedisct1** [comment]
The test performs 15 round, and I don't have individual timings of each round, but this is something I can add. But a cold start would be a bit annoying no matter what, especially with that kind of function.

**Comment by buu700** [comment]
Cool, sounds. Yeah, based on those results I don't think we can afford to treat total memory any differently. I just mean that if ALLOW_MEMORY_GROWTH literally never impacted memory growth until we exceeded the total memory, then it might make sense to enable (in addition to getting this issue fixed), since it would allow some additional flexibility and in production a temporary slowdown would generally be preferable to an error (although some may prefer the latter during development).

**Comment by jedisct1** [comment]
Results of individual rounds: there's no one-off slowdown except in some specific tests. It's just slower on all rounds.

Example timings for `ed25519_convert.log`:

Fixed memory size:
```
164000000000
160733333333
160800000000
160400000000
160600000000
160400000000
160200000000
160266666666
160666666666
160600000000
160200000000
160133333333
160933333333
160200000000
160133333333
PASS ed25519_convert.js (exit status: 0)
```

With memory growth:
```
586333333333
569066666666
567933333333
565933333333
566466666666
575133333333
580666666666
575200000000
574000000000
565666666666
571266666666
570800000000
579333333333
566800000000
570000000000
PASS ed25519_convert.js (exit status: 0)
```

For Argon2id:

Fixed
```
602800000000
596533333333
597866666666
597666666666
596000000000
595933333333
597600000000
595400000000
596400000000
596066666666
596666666666
596066666666
595866666666
595933333333
596066666666
PASS pwhash_argon2id.js (exit status: 0)
```

Variable
```
1115333333333
1102200000000
1110800000000
1111200000000
1105133333333
1107800000000
1094000000000
1126200000000
1117666666666
1101733333333
1096933333333
1105066666666
1096600000000
1098000000000
1106733333333
PASS pwhash_argon2id.js (exit status: 0)
```

Signatures (sign.c):

Fixed
```
622666666666
616333333333
619733333333
617200000000
615933333333
620866666666
618666666666
619666666666
621533333333
619200000000
620866666666
617333333333
617533333333
618266666666
618800000000
PASS sign.js (exit status: 0)
```

Variable
```
2183000000000
2126400000000
2121600000000
2122266666666
2128200000000
2116866666666
2126133333333
2145400000000
2125133333333
2124466666666
2138666666666
2122400000000
2126000000000
2130666666666
2129800000000
PASS sign.js (exit status: 0)
```

Ouch.

**Comment by jedisct1** [comment]
And these tests perform don't perform any dynamic memory allocations after the first round, and even during the first round, there are very few of them. They are almost exclusively doing computations. 

So, I'm not sure what the exact implications of memory growths are, but this is certainly not something we can use :(

**Comment by buu700** [comment]
Ah, well that really sucks then :/.

**Comment by openidauthority** [comment]
For those who want to follow this issue, see https://github.com/kripken/emscripten/issues/5925

**Comment by stevelacey** [comment]
Any way to get rid of the error then? Does it matter? Seems to work
