### ISSUE TITLE
Can't anyhow compile it (now in the correct project)

### ISSUE THREAD

**Issue by pzduniak** [jedisct1/libsodium#633]
I triple-checked that this is libsodium and not libsodium.js.

Having issues with all Node.js bindings, so I think it's somethign with libsodium itself. Currently trying on Alpine (but Debian didn't work either). Deps are as following (from a Dockerfile):

```RUN apk add --update --no-cache git make libtool autoconf automake gcc g++ libsodium libsodium-dev binutils build-base```

And the error is:

```make[3]: *** No rule to make target 'crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S', needed by 'crypto_stream/salsa20/xmm6/libsodium_la-salsa20_xmm6-asm.lo'. Stop.
make[3]: *** No rule to make target 'crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S', needed by 'crypto_stream/salsa20/xmm6/libsodium_la-salsa20_xmm6-asm.lo'.  Stop.
make[3]: Leaving directory '/app/node_modules/sodium-native/libsodium/src/libsodium'
make[2]: *** [Makefile:2925: install-recursive] Error 1
make[2]: Leaving directory '/app/node_modules/sodium-native/libsodium/src/libsodium'
make[1]: *** [Makefile:397: install-recursive] Error 1
make[1]: Leaving directory '/app/node_modules/sodium-native/libsodium/src'
make: *** [Makefile:511: install-recursive] Error 1```

**Comment by jedisct1** [comment]
Still not the correct project.

Your issue is about [sodium-native](https://github.com/sodium-friends/sodium-native), that includes its own copy of the libsodium source code.

Unfortunately, it looks like this copy is incomplete. Some files such as `crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S` are missing.

But these wrappers can use an installed version of libsodium. It compiles its bundled one only when libsodium is not already installed on the system.

So, you can install libsodium using a package if your distro ships recent packages (I think sodium-native requires version 1.0.15 at least), or using the instructions [here](https://download.libsodium.org/doc/installation/). Don't forget to type `ldconfig` after manual installation.

Then, `sodium-native` shouldn't require its own copy any more. But the solution would be to tell the `sodium-native` maintainers that some files are missing.
