### ISSUE TITLE
crypto_generichash_blake2b_final crashes on macOS

### ISSUE THREAD

**Issue by ektrah** [jedisct1/libsodium#651]
My unit tests for NSec crash on macOS without error message after updating the libsodium nuget package from 1.0.15 to to 1.0.16. I've narrowed it down to the `crypto_generichash_blake2b_final` function. This C# code reproduces the problem:

```csharp
byte[] key = new byte[crypto_generichash_blake2b_KEYBYTES];
byte[] input = new byte[123];
byte[] output = new byte[crypto_generichash_blake2b_BYTES];

crypto_generichash_blake2b_state state;
crypto_generichash_blake2b_init(out state, ref key[0], (UIntPtr)key.Length, (UIntPtr)output.Length);
crypto_generichash_blake2b_update(ref state, ref input[0], (ulong)input.Length);
crypto_generichash_blake2b_final(ref state, ref output[0], (UIntPtr)output.Length); // crash
```

Any ideas?

**Comment by jedisct1** [comment]
I don't see any changes in the blake2b code between these two versions that could explain this :(

The types used for the sizes look weird though. Is `(UIntPtr)` equivalent to `size_t`?
Also `input.Length` should be `unsigned long long`, not `unsigned long` (which `ulong` is probably equivalent to).

**Comment by ektrah** [comment]
This is the equivalent (but untested) C code:

```c
crypto_generichash_blake2b_init(&state, &key[0], (size_t)keyLength, (size_t)outputLength);
crypto_generichash_blake2b_update(&state, &input[0], (uint64_t)inputLength);
crypto_generichash_blake2b_final(&state, &output[0], (size_t)outputLength); // crash
```

**Comment by jedisct1** [comment]
I have no idea :( Do you have some details about the crash?

**Comment by jedisct1** [comment]
What is the size of `state`? Does is come from `crypto_generichash_statebytes()`?

**Comment by ektrah** [comment]
Crash report: [dotnet_2017-12-21-052225_Distillers-Mac.crash.txt](https://github.com/jedisct1/libsodium/files/1579319/dotnet_2017-12-21-052225_Distillers-Mac.crash.txt)

Looks like a segmentation fault.

The size of `state` is 384 and the return value of `crypto_generichash_statebytes()` is 384 as well.

**Comment by ektrah** [comment]
I've downloaded the 1.0.16 tarball and built libsodium on the macOS box. Same crash. Making this change in `crypto_generichash_blake2b_final` fixes it:

```diff
-    COMPILER_ASSERT(sizeof buffer == 64U);
-    STORE64_LE(buffer + 8 * 0, S->h[0]);
-    STORE64_LE(buffer + 8 * 1, S->h[1]);
-    STORE64_LE(buffer + 8 * 2, S->h[2]);
-    STORE64_LE(buffer + 8 * 3, S->h[3]);
-    STORE64_LE(buffer + 8 * 4, S->h[4]);
-    STORE64_LE(buffer + 8 * 5, S->h[5]);
-    STORE64_LE(buffer + 8 * 6, S->h[6]);
-    STORE64_LE(buffer + 8 * 7, S->h[7]);
-    memcpy(out, buffer, outlen);
+    #ifdef NATIVE_LITTLE_ENDIAN
+    memcpy(out, &S->h[0], outlen);
+    #else
+    #error Not NATIVE_LITTLE_ENDIAN
+    #endif
```

**Comment by jedisct1** [comment]
I don't get how that could make a difference.

Can you remove `CRYPTO_ALIGN(64)` in `src/libsodium/include/sodium/crypto_generichash_blake2b.h`, then `make clean` and recompile?

**Comment by ektrah** [comment]
Removing `CRYPTO_ALIGN(64)` fixes it.

**Comment by jedisct1** [comment]
That might be the problem. Does NSec ensure that the state is properly aligned?

**Comment by ektrah** [comment]
The state is aligned on 8 bytes, but not 64 bytes.

The libsodium documentation [says](https://download.libsodium.org/doc/hashing/generic_hashing.html): "64-bytes alignment is recommended for performance, but not required."

**Comment by jedisct1** [comment]
Can you try to make it aligned?

**Comment by ektrah** [comment]
I can [specify](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=netcore-2.0) an alignment of 64 bytes, but the struct still is only aligned on 8 bytes. So it seems my only option is to allocate a larger chunk of memory and align the struct inside that manually. I'd prefer not to do that.

**Comment by jedisct1** [comment]
Can you try both?

**Comment by ektrah** [comment]
Manually aligning the state on 64 bytes fixes it.

**Comment by jedisct1** [comment]
The compiler assumes that the structure is aligned, and with optimizations turned on,`STORE64_LE` produces `_mm_load_*` opcodes that assume aligned pointers.

We use `_mm_loadu_*` everywhere to support unaligned accesses, but that doesn't work around (totally legitimate) compiler optimizations. Using `memcpy()` instead here only works by accident. 

The documentation has been updated. 64 bytes alignment *is* required.

In spite of performance regressions on some CPUs, I may remove the alignment requirements in the next version, since it is cumbersome with non-C bindings.

**Comment by ektrah** [comment]
OK, thanks for helping me troubleshoot. I can live with the workaround until the next version.

Have you considered increasing `crypto_generichash_blake2b_statebytes()` and doing the manual alignment within each call of `crypto_generichash_blake2b_init/update/final`?

**Comment by jedisct1** [comment]
That's a great suggestion :)

**Comment by ektrah** [comment]
That would break if bindings move the state between calls, though (such as in languages with a GC). So dropping the alignment requirement is probably the best idea.

The change from "encouraged" to "must be 64-byte aligned" is a *big* breaking change. I'm sure other bindings will have trouble as well, since many non-C languages do not support alignments well that are greater than the size of the largest built-in type.

**Comment by jedisct1** [comment]
I'm more concerned about having the library compiled with a compiler that supports alignment attributes, that would be later used in applications compiled with another compiler that does not support these statements. If the type is directly used instead of `_statebytes()`, bad things can happen.

The change to "encouraged" is actually fairly recent. It used to be required. The 64-byte alignment requirement was there in the very first version, and I think virtually all bindings properly deal with it. If only because alignment is also required for `onetimeauth()` and `aes256gcm()`.

Tolerating unaligned pointers doesn't seem to be a good idea after all. It means that some applications would be perfectly safe on some versions of the library, and have an undefined behavior on previous versions. This is not great, especially considering the fact that people will keep using versions that are already obsolete for years, thanks to "stable" distributions.

In retrospect, I think the safest and least breaking change to do would be to trigger `sodium_misuse()` if the pointer is not aligned and the compiler used to compile the library supports alignment. This will make bindings immediately fail if they pass unaligned pointers instead of only failing on some platforms.

**Comment by ektrah** [comment]
+1 for `sodium_misuse()` on unaligned pointers if lifting the alignment requirement is not an option.

The alignment requirements of `onetimeauth` and `aes256gcm` don't seem to be documented.

**Comment by jedisct1** [comment]
[`A 16 bytes alignment is required for the address of ctx`](https://download.libsodium.org/doc/secret-key_cryptography/aes-gcm_with_precomputation.html).

This was indeed not documented for `onetimeauth`. Gonna fix this right away!
