### ISSUE TITLE
Behavioural change of hex2bin

### ISSUE THREAD

**Issue by blochberger** [jedisct1/libsodium#663]
The documentation states that

> The parser stops when a non-hexadecimal, non-ignored character is found or when `bin_maxlen` bytes have been written.

Assume the following code snippet, where `hex` starts with a non-hex character:

```c
const size_t  bin_maxlen = 4;
unsigned char bin[bin_maxlen];
unsigned char hex = "X00112233";
const size_t  hex_len = 9;
size_t        bin_len;
int result = sodium_hex2bin(&bin, bin_maxlen, hex, hex_len, /*ignore*/ 0, &bin_len, /*hex_end*/ 0);
```

Previously `result` was `0` as well as `bin_len`. Now `result` is `-1`, which according to the documentation means that not enough space was reserved (`bin_maxlen`).

Was this change expected and the documentation not updated or is this a bug? According to the documentation I would expect the previous case to be the correct one and consider this a bug.

**Comment by jedisct1** [comment]
Hi Max,

This is intentional, and happens because you have an incomplete input, but didn't provide a pointer to store where the input stopped being parsed. See 7423408cd33e4bab71b1ee5bef4dadd0eb05e7cd

This change was motivated by a previous issue.

Set `hex_end` to a non-`NULL` value, and it will return `0`. Without a `hex_end` pointer, it is assumed that the application expects the input to match the requested size.

Indeed, the documentation may need an update. Thanks a lot for pointing this out.

**Comment by jedisct1** [comment]
This has been clarified in the documentation.

Thanks!

**Comment by jedisct1** [comment]
The next version of the API will not have `bin_len` any more, but always returns the number of bytes: https://github.com/jedisct1/libhydrogen/wiki/Helpers#hexadecimal-encodingdecoding
