### ISSUE TITLE
Why isn't HAVE_ARC4RANDOM used on compilation?

### ISSUE THREAD

**Issue by jorbs** [jedisct1/libsodium#674]
I've compiled the library on a Mac OS X High Sierra but it stills using `/dev/urandom` instead of `arc4random*` functions. So I noticed that the compile flags for it are `__OpenBSD__` and `__CloudABI__`. I tested the stable release with `HAVE_ARC4RANDOM` and it worked. So why not use this flag?

**Comment by jedisct1** [comment]
On OpenBSD, `arc4random()` is actually a system call, and doesn't use RC4 any more.

On MacOS:
- `arc4random()` is not available on older versions of MacOS
- `arc4random()` seems to read /dev/random` to reseed itself, and opens/closes the file every time. Which is not safe in a `chroot()`ed environment and violates libsodium guarantees
- before MacOS 10.2, `arc4random()` was actually using RC4, which should not be used for cryptographic keys due to biases.
