### ISSUE TITLE
Question: How long to stable?

### ISSUE THREAD

**Issue by kalaspuffar** [jedisct1/libsodium#694]
Hi @jedisct1 

Not asking to expedite the process just wondering if there is a schedule for stable releases or something like that. libsodium-jni uses the stable build when it creates it's package so I need to wait for the fix to build a none minimal build first, then for the change in libsodium-jni to become active before I can start using libsodium for scrypt. I'm checking in once a day but it seems a bit redundant if you say release next month.

Best regards
Daniel

**Comment by jedisct1** [comment]
Do you mean how long before libsodium 1.0.17? Or libsodium 2.0? Or the next update to the stable branch?

In order to get bug fixes that don't change the API, you should just check out the stable branch.

This branch is usually more stable than releases themselves as it includes last-minute fixes.

As to the next release, I have no idea. Probably not anytime soon, since I'm quite busy with work right now, and my priority for that year is more to stabilize libhydrogen than develop libsodium.

**Comment by jedisct1** [comment]
As to libsodium 2.0, it will obviously be after libhydrogen 1.0 :)
