### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by RootUp** [jedisct1/libsodium#729]
Dear Team, 

Could some advise where to submit *security* bugs for `libsodium`.

Thanks!

**Comment by jedisct1** [comment]
Hi!

Can you submit a pull request with a fix, preferably based on the stable branch?

Thanks!

**Comment by RootUp** [comment]
Thank you @jedisct1 

Buffer over-read:

File: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_core/ed25519/ref10/ed25519_ref10.c#L569

i.e
`fe25519_copy(minust.yminusx, t->yplusx);`

Function does not check the second iterator for over-read conditions.

This function is often discouraged by most C++ coding standards in favor of its safer alternatives provided since C++14. Consider using a form of this function that checks the second iterator before potentially overflowing it.

For example:
```
/* copy pattern parameter to variable, may cause off-by-one overflow */
fe25519_copy(minust.yminusx, t->yplusx);
```

**Comment by jedisct1** [comment]
Looks like a generic diagnostic message from Flawfinder.

Flawfinder just greps for fixed strings. It doesn't understand anything to the control flow or even the syntax. While it can still be a useful tool, you really need to look at the actual code since most of its output is not only false positives, but also reports that don't make any sense in the actual context.

Old versions used to print the message you quoted when the string `copy` was found. This has been removed in recent versions, probably due to too many false positives.

The intent was to warn against a use of a potentially dangerous function of a C++ library called STL.

The function called here has `copy` in its name but has nothing to do with it.

Libsodium doesn't use the STL library and never will since it's written in a different programming language (C, not C++) in which STL doesn't exist.
