### ISSUE TITLE
crypto_secretbox_easy & crypto_secretbox_open_easy failing to encode/decode encripted text

### ISSUE THREAD

**Issue by ebalo55** [jedisct1/libsodium#732]
Hi,
I've tried using libsodium in a c++(14) environment and i have found a big issue, while calling the _crypto\_secretbox\_open\_easy_ and _crypto\_secretbox\_easy_ functions.
In the doc there's written that every time i encode a string of any lenght i will have another string of the same lenght but after some tests i have found that:
- The 2 lenght are always different but not by the amount of _crypto\_secretbox\_MACBYTES_
- The decoding function fail to decode **every** string with a lenght >= 8
- After the failure of the decoding function the encoded text is always pasted (probably a fallback?)
- The encoded size is always the same as the nonce size (= 24)
- The bin2hex function always return segmentation-fault

following the used code and the results:

[main.txt](https://github.com/jedisct1/libsodium/files/2185447/main.txt)
[executions.txt](https://github.com/jedisct1/libsodium/files/2185448/executions.txt)

**Comment by jedisct1** [comment]
Looks like this is an assignment that was given to you in order to learn the C++.

The issues you are having have little to do with libsodium. 

Try to study the basics of the language. Especially pay attention to how pointers works, what `sizeof()` does, what type it returns and how it generalizes. 

Try some simple things, completely without libsodium. Such as asking the user to enter two strings,  convert them to pointers, concatenate them and print the result.

Also, the first thing you should do when using libsodium is call `sodium_init()`. And read the doc again, paying attention to the examples.

Good luck!
