### ISSUE TITLE
libsodium_memzero with memory barrier

### ISSUE THREAD

**Issue by rurban** [jedisct1/libsodium#802]
You cite libsodium_memzero as secure by using a compiler barrier. This is not secure enough when sidechannel attacks can read the unflushed heap (meltdown), which is not being written by your memzero. It only protects your compiler optimizer from eliminating it it all.
 
You really need a full memory barrier (mfence). Not just lfence because you need to flush the write cache, and not just sfence, because most modern CPU microarchitectures are known to violate load-store ordering.
All other "secure" memzero/memset extensions are also insecure. A retpoline doesn't help you from protecting against heap sidechannels from another CPU or hyperthread. Securely written memory must be flushed.

A proper secure memzero implementation, the MEMORY_BARRIER can be taken from safeclib:
https://github.com/rurban/safeclib/issues/63
src/mem/mem_primitives_lib.h and src/mem/mem_primitives_lib.c, MIT licensed.

**Comment by jedisct1** [comment]
For this particular case, can you clarify why you would use a full memory barrier instead of an `sfence`?

**Comment by rurban** [comment]
sfence: When with mult. threads one read-cache still contains parts of the zero'd range, sfence alone will not flush the read-cache, only an lfence or mfence would do that.

**Comment by jedisct1** [comment]
That totally makes sense, thanks for clarifying.

That being said, adding a full memory barrier here comes at a non-negligible cost, especially since it is common to zero multiple disjoint values in a row. And I'm not sure that the actual benefits are worth it.

SPECTRE-like attacks can be conducted during all the time the secret is present, prior to zeroing. The required preconditions and the time window during which a full memory barrier could help, seem to be negligible compared to the actual lifetime of the secret.

And from an application perspective, if a secret is intended to be used over and over again, it won't be zeroed.

So, yes, a memory barrier would improve the perception that calling `memzero` makes the data unrecoverable after the function returns.

But adding a barrier to mitigate SPECTRE-like attacks is not enough (the secret can still be present in registers, or have been spilled on the stack) to make stronger guarantees, while having significant performance implications. `sodium_memzero` should be considered as best-effort, with reasonable tradeoffs.
