### ISSUE TITLE
SHA Extension / Intrinsics sha_ni

### ISSUE THREAD

**Issue by mattcollier** [jedisct1/libsodium#808]
Hello, here is some benchmarking that shows the benefits of using SHA extensions.

https://bench.cr.yp.to/impl-hash/sha256.html

The extensions are available on the `Zen` and `Cortex-A72` platforms shown there with the lower scores.
- http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.100097_0002_04_en/way1395175472464.html
- https://software.intel.com/en-us/articles/intel-sha-extensions

Here is the `ref` implementation indicated on the chart: https://github.com/floodyberry/supercop/tree/master/crypto_hashblocks/sha256

Here's more code that uses the extensions: https://github.com/noloader/SHA-Intrinsics

OpenSSL also implements the extensions.

Can any of this code be of benefit here?

**Comment by jedisct1** [comment]
These extensions only support SHA256, which is not used by any high-level APIs in libsodium.

SHA512 could benefit from an AVX-optimized implementation, but the benefits are not significant.

**Comment by mattcollier** [comment]
@jedisct1 Is this implementation of any use? https://github.com/noloader/SHA-Intrinsics/blob/master/sha512.c

**Comment by jedisct1** [comment]
Not really. It's very generic and I doubt it's faster than what we already have.

I'm not looking for existing implementations TBH, rather for time to possibly work on this (and opensource software in general). And right now, I don't have much, since finding a way to pay my rent has a much higher priority.

So, non-critical features like this are really low in the TODO-list.
