### ISSUE TITLE
Purpose of _sodium_alloc_init() Function

### ISSUE THREAD

**Issue by bingchengWong** [jedisct1/libsodium#820]
I am trying to port the libsodium into Xilinx SDK C Programming. I notice that within this _sodium_alloc_init() Function, it constantly tried to open/read device. However, as open/read function is not fully supported for the following directory "/dev/urandom". Will there be any effect if I were to skip the  _sodium_alloc_init() Function during sodium_init ? Thank you.

**Comment by bingchengWong** [comment]
To add on, the open function can be found in the link attached below:
https://github.com/Xilinx/embeddedsw/blob/master/lib/bsp/standalone/src/arm/common/gcc/open.c

**Comment by jedisct1** [comment]
The purpose of reading `/dev/urandom` is to collect random numbers.

If you remove the call to `_sodium_alloc_init()`, the canary used to check for overflows in memory allocation function won't be set, defeating the purpose of the guarded memory functions.

But random numbers are required for more operations. Namely, key generation and nonce generation. If you remove this and returns a constant or uninitialized buffers, half the library will be broken, or provide absolutely zero security.

For such platforms, I'd suggest porting [libhydrogen](https://libhydrogen.org) instead of libsodium, even though you will still need to figure out how to gather random bits on the target device.
