### ISSUE TITLE
How should I choose between "Public-key Cryptography" and "Key Exchange + Secret-key Cryptography" ?

### ISSUE THREAD

**Issue by GreatFireWall** [jedisct1/libsodium#821]
In other words, what are the specific differences or advantages and disadvantages between the two?

**Comment by jedisct1** [comment]
Key exchange involves public-key cryptography as well.

I guess you are referring to using `crypto_box()/crypto_box_seal()` vs using `crypto_kx() + {secretstream, aead or secretbox}`.

`crypto_box()` is exactly the same as doing a key exchange followed by `secretbox()`. This is a legacy API.

`crypto_box_seal()` is useful if the server doesn't have to know the client public key in advance. Any client can send a message and each message is encrypted using a throw-away key.

Most of the time, you want to use`crypto_kx()` + a symmetric cipher with the resulting secret key instead of these.

This offers better security and more flexibility, as you can use the session key with different functions, including sending a sequence of messages with `crypto_secretstream()`.

This is also more future-proof as different key exchange mechanisms may be added later.
