### ISSUE TITLE
ETA for a 1.0.18 release?

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#823]
Hi @jedisct1, is there an ETA for a 1.0.18 release? We would like to use some functionality that was introduced in 1.0.17, but we also want the commit that removes the `__attribute__((nonnull))` checks from a bunch of public APIs, which will only be available in 1.0.18. Thanks!

CC: @kevinlewi

**Comment by jedisct1** [comment]
Hi Ilya,

Hard to give any ETA besides "soon".

The Ristretto code needs a bit more testing, same for the PRG code. The changes made since version 1.0.17 may have introduced portability issues.

I was also planning to add wasm32-wasi as an officially supported platform starting with version 1.0.18, but that also requires a bit more testing (I have a case where the behavior changes when optimizations are turned on or off. Likely a bug in the wasm compilation toolchain, but this requires more investigation).

What functionality from 1.0.18 are you looking for?

Removing the `__attribute__((nonull))` checks might be acceptable in the `stable` branch.

**Comment by ivmaykov** [comment]
@jedisct1 we need the finite field arithmetic functions: https://libsodium.gitbook.io/doc/advanced/point-arithmetic

**Comment by jedisct1** [comment]
With the exception of `scalar_mul()`, these functions are already available in version 1.0.17.

**Comment by ivmaykov** [comment]
Right, but I believe that the 1.0.17 release has the `__attribute__((nonnull))` checks that caused issues in our code base and prompted me to submit #804.

**Comment by ivmaykov** [comment]
How (un)safe is it to use a non-released version of LS in prod code? I.e. something between 1.0.17 and the eventual 1.0.18?

**Comment by jedisct1** [comment]
The `stable` branch should be always safe to use.

The `master` branch should be acceptable at this point, since most of the known remaining issues are about portability.

**Comment by kevinlewi** [comment]
Hi @jedisct1, we would really appreciate including the removal of the ``__attribute__((nonnull))` checks in the ``stable`` branch of 1.0.17!

**Comment by jedisct1** [comment]
Done :)

**Comment by ivmaykov** [comment]
@jedisct1 thanks for being so responsive!

**Comment by kevinlewi** [comment]
@jedisct1 Awesome!! I second Ilya's comment :)

**Comment by jedisct1** [comment]
np.

Looking forward to seeing what you are going to build!

**Comment by ivmaykov** [comment]
Sure! I'm hoping we will be able to open-source it.
