### ISSUE TITLE
ristretto255 APIs

### ISSUE THREAD

**Issue by FiloSottile** [jedisct1/libsodium#836]
The ristretto255 authors and I were very happy to see the ristretto255 implementation in libsodium! We also spent some time thinking about APIs, and some feedback came up.

The main thing is that encoding and decoding is cheap but not free, so it's not meant to be done at every operation. The idea is to decode or hash into elements represented by an opaque type, do additions, subtractions and multiplications on that type, and then encode it on the way out.

It is also unclear when the two `crypto_scalarmult_ristretto255` APIs fail: I assume it's if either n is 0, p is the zero element, or p is not a valid encoding, but they are not all called out. (Also, not entirely sure why fail on the zero values. Our libraries don't.)

Error conditions would also be easier if using an opaque type because effectively only the decode operation can fail, and all other operations always succeed because there is no way to generate an invalid element value (as opposed to an invalid encoding).

Finally, as a nit, the docs and the `crypto_core_ristretto255_is_valid_point` API refer to elements as points and encodings as compressed points. We like to use "element" and "encoding" to preserve the abstraction. Also, the spec calls the point at infinity the "zero element".

You can look at the new Go implementation for an example:
https://godoc.org/github.com/gtank/ristretto255

There is also a new "API Considerations" section in version -01 of the draft:
https://tools.ietf.org/html/draft-hdevalence-cfrg-ristretto-01#section-4

/cc @hdevalence

**Comment by jedisct1** [comment]
Hi Filippo,

Having a single representation is a [design choice](https://download.libsodium.org/doc/internals#avoiding-type-confusion), and the Ristretto-related APIs should be consistent with other APIs.

At some point, [wasm-crypto](https://github.com/jedisct1/wasm-crypto), in which Ristretto255 is the default group used for everything, adopted an API similar to the one you describe.

Points and scalars were opaque structures, and packing/unpacking was only done when necessary. This is still sitting somewhere in a [branch](https://github.com/jedisct1/wasm-crypto/tree/publicpoint).

Turns out that this was causing serious usability issues.

AssemblyScript (actually WebAssembly) and Javascript (or whatever tries to exchange data with Wasm) can only pass integers to each other, and don't have access to the same memory segments.

So, an encoded elements already requires Javascript to keep two representations of the same thing: one "as Javascript", and another one "as an offset in the wasm module linear memory".

Having to juggle with two representations of the same thing is already the source of many bugs. Weak typing (JS side) and the fact that `NULL` can be dereferenced (Wasm side) don't help.

If an element must be explicitly encoded/decoded, this introduces more complexity.

We now have to keep 4 variables, for 4 different representations, for a single element. This adds a lot of conversion overhead, in addition to being a nightmare to use even for simple applications. Not to mention memory management, that has to be done manually in AssemblyScript.

What if we screw up and use `element_as_a_wasm_offset` instead of `element_as_its_internal_representation_and_as_a_wasm_offset`?

Remember that there are no pointers. All we provide to wasm functions are integers, that can possibly be memory offsets. Type checking is nonexistent.

So, the webassembly module will assume that this is an element in its internal representation, while it is not. This can have catastrophic implications.

This is not limited to Webassembly.

Interfacing with a C library from another language breaks type safety. Opaque structures are not always easy to manage.

People will also irremediably do things such as storing/sending the internal representation of elements "because it's faster". This will leak internal data, will not be portable across architectures and versions, but they will do it, because the language will allow them to do it.

Which is why packing/unpacking is always done. Elements are always represented the same way in the public API. Performance has less importance than ease of use.

I've been trying to convince myself that having an opaque representation and explicit packing/unpacking was a good thing, but after some really bad experience with such an API in wasm-crypto, I switched back the API to something similar to libsodium's.

**Comment by jedisct1** [comment]
That documentation page was updated, thanks!

`scalarmult_ristretto255()` fails on zero values so that it can be a drop-in replacement for `scalarmult_curve25519()`. We need these APIs to be consistent.

**Comment by tarcieri** [comment]
> I've been trying to convince myself that having an opaque representation and explicit packing/unpacking was a good thing

The main problems with compressing every time are that Ristretto is particularly well-suited for protocols which are both complex (e.g. Bulletproofs) and composable (e.g. doing additional operations over the same field within an algebraic circuit materialized as a Bulletproof).

It sounds like you're dealing with a number of environments where exposing an opaque representation of Ristretto elements would be a pain. So how about the "Doctor, it hurts when I..." approach and don't expose the opaque representation in these environments? You can still have APIs which work exactly as libsodium does today: the opaque representation could be a purely additive change, only available to C programmers using libsodium and not exposed in `wasm-crypto`, but for the compressing/"byte-oriented" APIs, in libsodium they could be implemented as point compression on the opaque type. `wasm-crypto` could do the same thing, the only thing being operations on uncompressed Ristretto elements wouldn't be accessible from JS.

**Comment by jedisct1** [comment]
This will make the API more confusing, having multiple ways to achieve the same thing, with no benefits besides slightly better performance. Really, I'd rather keep things simple and working in a similar way in all environments.

**Comment by tarcieri** [comment]
> This will make the API more confusing, having multiple ways to achieve the same thing

That's true, however it also seems par for the course with libsodium where some of the initial APIs had somewhat similar limitations, e.g the original `crypto_hash_*` APIs versus the IUF API provided by `crypto_generichash_init`/`_update`/`_final`.

Just as IUF modes help people who are trying to hash things that are bigger than what can fit in RAM, allowing group operations on uncompressed Ristretto group elements benefits anyone who wants to skip point compression for every single group arithmetic operation in protocols which do significant numbers of group operations. For Ristretto, I think those sorts of protocols are the primary use case / "killer app", and though it's just an optimization, it's an important optimization for Ristretto's key use cases.

**Comment by jedisct1** [comment]
This is an optimization that may be added in the future, but I'd rather not introduce this yet. Not having APIs operating on uncompressed elements doesn't make Ristretto useless, if only for interoperability with wasm-crypto.
