### ISSUE TITLE
ec multiplication is slow

### ISSUE THREAD

**Issue by narodnik** [jedisct1/libsodium#858]
Hello, I wrote a benchmark which generates 100,000 scalar secrets then loops through them multiplying them by a point using `crypto_scalarmult_ed25519`.

I compared the implementation here with the original djb NaCl and bitcoin-core libsecp256k1 library. Note: curve25519 is supposed to be faster than secp256k1. Here's my results:

```
libsodium 25519 took: 13432 ms
libsodium 25519 done.
nacl 25519 took: 6344 ms
nacl 25519 done.
secp took: 7420 ms
secp done.
```

This operation with libsodium is more than 2x slower than with nacl (benchmark compiled against amd64 build of nacl).

**Comment by jedisct1** [comment]
`crypto_scalarmult_ed25519()` doesn't clamp the scalar but performs an extra scalar multiplication to unconditionally check that the point is on the main subgroup.

Also, you may be confusing Ed25519 and X25519, since NaCl doesn't expose scalar multiplication over Ed25519. The equivalent to NaCl's `crypto_scalarmult()` is... `crypto_scalarmult()`.

**Comment by narodnik** [comment]
Got you. I replaced that call and now get similar performance to djb implementation:
```
sodium 25519 took: 6614 ms
sodium 25519 done.
djb 25519 took: 6343 ms
djb 25519 done.
```
Thanks

**Comment by jedisct1** [comment]
Also, don't forget to call `sodium_init()` before anything else.

**Comment by narodnik** [comment]
Thanks
