### ISSUE TITLE
Ed25519 strange behavior on wasm32-wasi

### ISSUE THREAD

**Issue by kpp** [jedisct1/libsodium#879]
Potential bugs in `crypto_sign_ed25519` and `crypto_sign_ed25519_detached`:

See https://github.com/sodiumoxide/sodiumoxide/pull/376#issuecomment-539775557

With `WASMER_DIR=${HOME}/.wasmer PATH=${HOME}/.wasmer/bin:/opt/wasi-sdk/bin:${HOME}/.cargo/bin:$PATH dist-build/wasm32-wasi.sh` ed25519 fail, with https://github.com/sodiumoxide/sodiumoxide/pull/379 they pass.

**Comment by jedisct1** [comment]
Hi,

`ED25519_NONDETERMINISTIC` is set for the WASI builds.

This creates non-deterministic signatures to protect against memory corruption/fault attacks, because I don't trust at all some platforms the wasm32-wasi version will run on.

These signatures can still be verified by any standard Ed25519 implementation.

**Comment by kpp** [comment]
How can we fix our tests?

**Comment by jedisct1** [comment]
If some of your tests assume that signatures are deterministic, skip them on `wasm32-wasi`, or change the polarity of these tests to verify that signing the same message twice produces different signatures, that still verify using the same public key.
