### ISSUE TITLE
PAKE and server-side PAKE (SRP)

### ISSUE THREAD

**Issue by SoniEx2** [jedisct1/libsodium#907]
it would be highly appreciated to have a PAKE/SRP-based alternative to argon2/bcrypt/scrypt/whatever. Bonus points is that this gives an upgrade path towards client-server PAKE if so desired.

Having PAKE where you have access to the password is no more secure than argon2/bcrypt/scrypt, but the upgrade path is key. With argon2/bcrypt/scrypt you can't switch to PAKE later, but if you already have PAKE, even if it's just on the server, you can always switch to client-server PAKE.

**Comment by kevinlewi** [comment]
Within Facebook, we have an implementation of the [OPAQUE protocol](https://www.ietf.org/id/draft-krawczyk-cfrg-opaque-03.txt) built on top of the [Ristretto](https://libsodium.gitbook.io/doc/advanced/point-arithmetic/ristretto), and we would be happy to share it if there is interest. See [this post](https://mailarchive.ietf.org/arch/msg/cfrg/1QQ_FfRsOxvoLGqX0t48WLTMSNU) for why we are interested in this at Facebook.

However, it is also worth noting that the standardization process for aPAKEs is not yet complete.

ccing @ivmaykov

**Comment by jedisct1** [comment]
There is a [SPAKE2+EE](https://github.com/jedisct1/spake2-ee) implementation. I also have a PAKE implemented as an example for [wasm-crypto](https://github.com/jedisct1/wasm-crypto) ([here](https://github.com/fastly/terrarium-templates/tree/master/105_access_control_example)), also using Ristretto.

These are better kept are separate projects (at least from libsodium), if only because there isn’t any standard yet.

**Comment by SoniEx2** [comment]
is scrypt standard? and yet, you have scrypt.
