### ISSUE TITLE
to autogen or not to autogen

### ISSUE THREAD

**Issue by AxelNennker** [jedisct1/libsodium#918]
libsodium-1.0.18 comes with a configure script
the stable branch here comes with a configure script
the master branch does not come with a configure script

All have the version number 1.0.18

Will the next release come without a pre-generated configure script?

I would prefer it that way because creating configure on macos results in a successful build for me while using the current configure script does not work.

I am using [sodiumoxide-0.2.5 while building libindy](https://github.com/AxelNennker/indy-sdk/tree/sodiumoxide_0.2.5) and that fails because [sodiumoxide](https://github.com/sodiumoxide/sodiumoxide) uses the [libsodium-sys](https://github.com/sodiumoxide/sodiumoxide/tree/master/libsodium-sys) crate which uses the pre-generated configure script.

So, if you release 1.0.19 without the configure script I will create a PR to sodiumoxide to generate it using autogen.sh which would make the building of libindy succeed on macos (libtool issues, I think).

**Comment by jedisct1** [comment]
You should never ever have to run `autogen`. Additional tools such as `libtool`, `autoconf` and `automake` are not required.

All tarballs include everything required to compile the software. This includes releases and stable versions, has been the case since the project exists and this is unlikely to ever change.

Documentation on installing libsodium from source: https://download.libsodium.org/doc/installation

The `master` branch is broken, untested, unfinished development code that you should never use unless you are planning to contribute code.

**Comment by AxelNennker** [comment]
Sorry for posting on a closed issue...

I am using this from rust ([sodiumoxide](https://github.com/sodiumoxide/sodiumoxide)) which automatically builds [libsodium 1.0.18 from source](https://github.com/sodiumoxide/sodiumoxide/tree/master/libsodium-sys) and that does not work on macos without autogen.

**Comment by jedisct1** [comment]
So this is a bug in that crate. [libsodium-sys-stable](https://crates.io/crates/libsodium-sys-stable) never required `autogen.sh` and the other tools it implies.

**Comment by AxelNennker** [comment]
I think that it is a MacOS thing in libsodium.

When I compiled libsodium 1.0.18 from source on my mbp it failed until I called autogen
