### ISSUE TITLE
How to use a data structure that defined in sodium/private?

### ISSUE THREAD

**Issue by nitrieu** [jedisct1/libsodium#921]
Hi,

I want to write a function which uses `fe25519` and its related functions. I see that  `fe25519` is defined in `[private/ed25519_ref10.h](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/private/ed25519_ref10.h#L15)`

- I tried to add `ed25519_ref10.h` to [sodium.h](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium.h), and then  include this header in my visual studio project, but it doesn't work. The error is 

> Cannot open include file: 'private/common.h': No such file or directory

Trying adding all headers of private folder to sodium.h doesn't help. I guess that I can't call anything from private folder.

- I tried another way to do it by writing my function inside libsodium. By doing so, I can call `fe25519`, however, I get a problem with statically link:

> LNK2019	unresolved external symbol **link_test_test** referenced in function 

Note that I can statically link libsodium to my project if I don't change anything inside libsodium 

![image](https://user-images.githubusercontent.com/16380791/73234890-eee63c80-4140-11ea-9afd-b37412eec4a1.png)

![image](https://user-images.githubusercontent.com/16380791/73234904-002f4900-4141-11ea-9580-c366c155dd49.png)

**Comment by jedisct1** [comment]
In Visual Studio, symbols from a library need to be exported in order be visible.

In order to do so, add `__declspec(dllexport)` before the prototype.

In libsodium, this can also be done with the `SODIUM_EXPORT` macro.

But if you only need field arithmetic, I'd recommend using [fiat-crypto](https://github.com/mit-plv/fiat-crypto) instead. For that field, you don't even need to install the code generator, as a [pregenerated implementation](https://github.com/mit-plv/fiat-crypto/blob/master/curve25519_64.c) is included.
