### ISSUE TITLE
Pointer comparison(s)

### ISSUE THREAD

**Issue by tankf33der** [jedisct1/libsodium#934]
I did research and learned how to split sources of library to be able run single test(s) under full control. This is not last issue about this "audit". TIS-interpreter and compcert found issue [here](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c#L34) when running [this](https://github.com/jedisct1/libsodium/blob/master/test/default/xchacha20.c#L424) function from xchacha20.c file.

TIS:
```
xchacha20/secretbox_xchacha20poly1305.c:34:[kernel] warning: pointer comparison: assert \pointer_comparable((void *)c, (void *)m);
                  stack: crypto_secretbox_xchacha20poly1305_detached :: xchacha20/secretbox_xchacha20poly1305.c:85 <-
                         crypto_secretbox_xchacha20poly1305_easy :: xchacha20/test_xchacha20.c:256 <-
                         tv_secretbox_xchacha20poly1305 :: xchacha20/test_xchacha20.c:441 <-
                         main
[value] Stopping at nth alarm
[value] user error: Degeneration occurred:
                    results are not correct for lines of code that can be reached from the degeneration point.
```

compcert:
```
Stuck state: in function crypto_secretbox_xchacha20poly1305_detached, expression
  <ptr> > <ptr> && (unsigned long long) c - (unsigned long long) m < mlen
    || (unsigned long long) m > (unsigned long long) c
         && (unsigned long long) m - (unsigned long long) c < mlen
Stuck subexpression:
  <ptr> > <ptr> && (unsigned long long) c - (unsigned long long) m < mlen
    || (unsigned long long) m > (unsigned long long) c
         && (unsigned long long) m - (unsigned long long) c < mlen
ERROR: Undefined behavior
```

codebase where this trick used:
```
./src/libsodium/crypto_secretbox/crypto_secretbox_easy.c
	crypto_secretbox_detached()
	crypto_secretbox_open_detached()

./src/libsodium/crypto_secretbox/xchacha20poly1305/secretbox_xchacha20poly1305.c
	crypto_secretbox_xchacha20poly1305_detached()
	crypto_secretbox_xchacha20poly1305_open_detached()
```

**Comment by jedisct1** [comment]
This works fine on all supported platforms.

Feel free to submit actual code to improve the implementation, but just copy/pasting the output of tools doesn't help much.

**Comment by LoupVaillant** [comment]
Two reputable, independent tools reported the same undefined behaviour. Maybe they're both incorrect, but that kind of thing makes me nervous.

Clearly, the code is attempting to avoid comparing pointers (which is undefined) by converting them to an integer type first. Surprisingly though, both TIS and CompCert think that doesn't count, interpret those pointers *as such*, and conclude "undefined". We could worry about whether GCC or Clang might reach the same conclusion at some point in the future.

Perhaps they already have. Incremental compilation then prevents them to notice that those pointers sometimes point to different objects. Under the usual assumption that undefined behaviour does not exist, compilers then only consider the case of pointers pointing to the same object. In machines with a flat memory model (likely "all supported platforms"), that works.

It's not clean, though. Unless Libsodium is not intended to be compiled from source, I would personally think this through for a minute. Perhaps the code should not be changed, but a comment explaining why the tools are wrong (or why undefined behaviour is not a problem), might help future audit efforts.

---

Incidentally, I believe I have spotted off by one error in that code:

    if (((uintptr_t) c > (uintptr_t) m &&
         (uintptr_t) c - (uintptr_t) m < mlen) ||
        ((uintptr_t) m > (uintptr_t) c &&
         (uintptr_t) m - (uintptr_t) c < mlen)) { /* LCOV_EXCL_LINE */

I believe you meant to use non-strict inequality when ensuring the buffers are disjoints?

    if (((uintptr_t) c > (uintptr_t) m &&
         (uintptr_t) c - (uintptr_t) m <= mlen) ||
        ((uintptr_t) m > (uintptr_t) c &&
         (uintptr_t) m - (uintptr_t) c <= mlen)) { /* LCOV_EXCL_LINE */

The strict inequality is understandable if `mlen` accounts for the presence of a terminating null character, but these are binary buffers, right? Whatever optimisation you're trying to accomplish won't apply itself if the input and output buffers stand right next to each other, as I assume they often do.

(I believe we can ignore the `mlen == 0` possibility, since `memmove` is unnecessary in this case.)

**Comment by jedisct1** [comment]
Strict inequality is what we want here. If the buffers stand right next to each other, there is no overlap, no so need to copy anything.

**Comment by LoupVaillant** [comment]
_<facepalm>_ I flipped the comparison, sorry. Got it now.
