### ISSUE TITLE
Signed symmetric encryption.

### ISSUE THREAD

**Issue by AlastairGrowcott** [jedisct1/libsodium#938]
Hi, there.

Firstly, apologies if this is the wrong place for this. I couldn't find anywhere else.

I am not an expert on encryption, but I have an encryption use case that keeps cropping up and is never supported by any high level APIs in libraries. Maybe it has an intrinsic weakness I am unaware of.

Albert wants to send an encrypted message to a group. Because it is a group encrypting with a public key is not appropriate as the private key would need to be shared amongst all members of the group. It is also not appropriate to have multiple key pairs and encrypt the message multiple times. I am currently doing this with both libsodium and libgcrypt by having a keypair for signing and using symmetric encryption with a second secret key. I would prefer to do this by encrypting with the private of the keypair and having the group members keep the public key secret as it reduces the number of keys to manage.

As a real world example, I am currently working on a licensing mechanism. I want to generate information in XML format as to what the user has paid for (which plugins, which version(s), end date, etc.). I want to encrypt the XML. While I am not that worried about anyone finding out what the contents of the licence are I would prefer to keep it private. Lastly I want to sign it to ensure that no-one can generate their own licences. The licensing server will keep the private key and store it securely and safely (hopefully). The application, distributed to customers, will contain the public key. It will be embedded in a way that makes it difficult to find (hopefully), but obviously cannot be guaranteed secret. If anyone wants to find it badly enough, they will. That's fine. I'm just trying to protect against casual interest. If I use a separate symmetric key, that too will end up being stored in the application and so will be vulnerable in the same way.

1) Is it even possible to encrypt with a private key so that only the public key can decrypt it and, by getting valid data, verify the source?
2) Is it likely that this library might implement a simplified API to either encrypt with a symmetric key and sign with a private key, or to just encrypt with the private key? Plus the corresponding decrypt API of course?
3) Is there an alternative I am unaware of that works better.

Also, it would be nice to have a version of crypto_secretbox_easy() that automatically stored the nonce in the output to save having to manually concatenate the encrypted data and the nonce. Even better, have the nonce automatically randomly generated and remove an input parameter. You could use the same API and detect a null pointer for the nonce to determine to automatically generate and include the nonce in the output.

**Comment by jedisct1** [comment]
> Is it even possible to encrypt with a private key so that only the public key can decrypt it

A public key is public. So encrypting with public data would be equivalent to no encryption at all.

> verify the source

`crypto_box` verifies the source. Maybe the [FAQ](https://download.libsodium.org/doc/quickstart) section of the documentation can help.

> Is it likely that this library might implement a simplified API to either encrypt with a symmetric key and sign with a private key

You generally want to do it the other way round, sign (including the public key of the recipient), then encrypt, so that the sender can prove that it was aware of what was signed.

>  with a private key, or to just encrypt with the private key

`crypto_box` doesn't encrypt with a private key, but with a private key and the recipient's public key.

> Also, it would be nice to have a version of crypto_secretbox_easy() that automatically stored the nonce in the output to save having to manually concatenate the encrypted data and the nonce.  Even better, have the nonce automatically randomly generated and remove an input parameter. 

It already exists: https://download.libsodium.org/doc/secret-key_cryptography/secretstream

**Comment by LoupVaillant** [comment]
I stumbled on a Real World Crypto 2020 talk about handling large groups. I don't remember which session, though.

If the groups are small enough, you can easily encrypt a message in `O(M+G)` (no pun intended), where G is the size of the group, and M the size of the message. You still need to know each member's public key, though.

Basically, instead of encrypting the message G times (that would be `O(M×G)`), you encrypt the message with a random symmetric key, and you encrypt that key for each recipient.

Let's say Alice wants to encrypt a message to Bob, Robert, and Sponge. She would proceed thus:

- Generate a random master key K.
- Encrypt the message M with K. (the result is ciphertext C and tag T)
- Encrypt K with Bob's key (the result is BK)
- Encrypt K with Robert's key (the result is RK)
- Encrypt K with Sponge's key (the result is SK)
- Send (BK || RK || SK || C || T) to the group.

Beware that I have omitted a number of critical "details" such as what "encrypt with Bob's key" means (read up the manual on [crypto_box](https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption)), forward secrecy (you need ephemeral keys, ratchets…), and authentication (done right, key exchange is generally enough, but you may want to use signatures as well).
