### ISSUE TITLE
Bigger keys, please.

### ISSUE THREAD

**Issue by AlastairGrowcott** [jedisct1/libsodium#939]
As far as I can tell the sodium_crypto_secretbox() APIs use a 256 bit key. The sodium_crypto_sign() API uses a 512 bit key. 2048 bit keys have been around for ages.

Is there a reason that libsodium uses such small keys?

Other crypto libraries allow you to choose your encryption algorithm and key size. Is there an API in libsodium that allows the same?

**Comment by emilbayes** [comment]
You are comparing apples to oranges. Libsodium uses elliptic curves, namely Ed25519 for signing and Curve25519/X25519 for encryption, which has 128-bit security level at 256-bit keys. You are thinking of RSA when talking about 2048 bits, which is completely different.

**Comment by enkore** [comment]
secretbox is actually not even asymmetric; it's symmetric authenticated encryption. Symmetric encryption very rarely sees use of keys in excess of 256 bits. There were never many algorithms which supported more, and most which did, are very old and weak algorithms like RC4. The reason is that there simply isn't any point in larger keys.

**Comment by AlastairGrowcott** [comment]
Thank you for the information and for taking the time to answer my question. I have to admit to total unfamiliarity with elliptic curve cryptography. I will go and do some research.
