### ISSUE TITLE
Watchkit Xcode 12

### ISSUE THREAD

**Issue by marwan87** [jedisct1/libsodium#994]
ld: warning: ignoring file ..../Pods/Sodium/Sodium/libsodium/libsodium-watchos.a, missing required architecture arm64 in file ..../Pods/Sodium/Sodium/libsodium/libsodium-watchos.a

Is there a work around for this ? or fix I can't run it on the simulator, I've tried adding the excluded architectures. 

I get around 103 fatal errors

**Comment by jedisct1** [comment]
This is off-topic, but the current version of Cocoapods has a couple bugs that prevents things such as the libsodium xcframework from being useable. Version 1.10.0 should fix this.

That being said, new versions are unlikely to be published on Cocoapods any longer since the Swift Packages Manager is a far better option.

So, use the Swift Package Manager, as documented https://github.com/jedisct1/swift-sodium
